datasets_params:
  derisi_FUN:
    hidden_dims:
    - 63
    - 160
    - 122
    - 106
    - 165
    - 129
    lr_values:
    - 0.002194847017262424
    - 0.0020963936573630947
    - 0.002339985922903689
    - 0.002786204118493528
    - 7.050456112057789e-05
    - 1.1313885063788805e-06
    dropout_values:
    - 0.44649883614508684
    - 0.3294685831274216
    - 0.3591477591055273
    - 0.721409598669826
    - 0.4229732504625613
    - 0.7554292590658488
    num_layers_values:
    - 2
    - 3
    - 1
    - 1
    - 1
    - 2
    weight_decay_values:
    - 0.00014031027742186214
    - 7.382124171780689e-05
    - 5.2651529723251864e-05
    - 0.0036323477273793405
    - 0.0029629377553706407
    - 2.04873145887481e-06
  cellcycle_GO:
    hidden_dims:
    - 88
    - 98
    - 176
    - 77
    - 215
    - 205
    - 159
    - 189
    - 106
    - 133
    - 116
    - 98
    lr_values:
    - 0.0006565343894840549
    - 0.00011621411536757123
    - 5.496129730807693e-05
    - 3.230278088220123e-05
    - 3.0484472408509482e-05
    - 0.0002645821456122371
    - 0.0066559105506583316
    - 2.097913597581292e-06
    - 0.0014108168447721024
    - 3.702464720812177e-05
    - 1.0009124420202875e-06
    - 0.007060069421684927
    dropout_values:
    - 0.5941028463275558
    - 0.4620974297382997
    - 0.6866360294330291
    - 0.3717666247413519
    - 0.3496246756243531
    - 0.42763038687515253
    - 0.7330529384309922
    - 0.4480589901996266
    - 0.7031364602619499
    - 0.3786770218339035
    - 0.6659774969590581
    - 0.6784346307860231
    num_layers_values:
    - 3
    - 2
    - 3
    - 1
    - 3
    - 2
    - 2
    - 1
    - 2
    - 3
    - 2
    - 1
    weight_decay_values:
    - 0.00039864417182114393
    - 0.003602560319086878
    - 2.4558013780787856e-05
    - 0.009705799065235336
    - 6.987889991842371e-06
    - 0.00029671876399137685
    - 2.1176456803792382e-05
    - 0.0005324558989751638
    - 0.0011268472329622541
    - 0.00016402501964324316
    - 0.005130741848312491
    - 0.0035017332800596165
  expr_GO:
    hidden_dims:
    - 1248
    - 882
    - 1659
    - 1073
    - 598
    - 596
    - 859
    - 1325
    - 1389
    - 939
    - 1284
    - 956
    lr_values:
    - 3.1719783300319724e-06
    - 0.004871935477972589
    - 0.00010795043281375042
    - 0.0003157228773215717
    - 0.0003240356171368167
    - 5.849301280743652e-06
    - 5.125410908110679e-05
    - 2.7501995465547165e-05
    - 1.3682597148233825e-05
    - 1.3195781575523405e-06
    - 0.0018948677524610001
    - 0.00021334871204333866
    dropout_values:
    - 0.5760998123220529
    - 0.7132906938346917
    - 0.5583999589843791
    - 0.45557120250318067
    - 0.4812341247065934
    - 0.4593300568755334
    - 0.38583609580842765
    - 0.43943268127791446
    - 0.3418595191091285
    - 0.6761126037533463
    - 0.45754033744524825
    - 0.7405435274645576
    num_layers_values:
    - 3
    - 1
    - 2
    - 2
    - 2
    - 2
    - 1
    - 1
    - 1
    - 1
    - 3
    - 3
    weight_decay_values:
    - 7.852352738611497e-06
    - 0.0001269464789804227
    - 0.0007599653725438442
    - 3.6966879503849157e-06
    - 0.00020347565997557967
    - 5.8760864089380655e-06
    - 4.058228889435107e-05
    - 0.0004989076992748165
    - 0.00021494813101325663
    - 0.0074069904720962965
    - 3.865218440422635e-06
    - 0.0005398948925880415
  eisen_GO:
    hidden_dims:
    - 104
    - 105
    - 146
    - 141
    - 166
    - 130
    - 85
    - 222
    - 86
    - 205
    - 215
    lr_values:
    - 0.00025740305495816206
    - 2.8025262148129552e-05
    - 0.001510889272757993
    - 0.0002581053034707459
    - 1.4470860079644188e-06
    - 3.574023926099506e-06
    - 0.0027083578597570145
    - 3.0785492012328114e-05
    - 0.0015623179046978805
    - 0.0009196582461640799
    - 0.005133362583266659
    dropout_values:
    - 0.4406428092294506
    - 0.7328853724568211
    - 0.31632665732819487
    - 0.38424006048803727
    - 0.3200369958499511
    - 0.6608231603450296
    - 0.6082203205974269
    - 0.6212942474048971
    - 0.6804681957414377
    - 0.5237892007290696
    - 0.4240570541198738
    num_layers_values:
    - 1
    - 2
    - 1
    - 1
    - 2
    - 3
    - 2
    - 3
    - 1
    - 1
    - 1
    weight_decay_values:
    - 1.1240641052978139e-05
    - 0.0008376207012258024
    - 0.009401001888443308
    - 1.5093934165114609e-06
    - 1.1550095608377999e-05
    - 0.0006137405365671587
    - 1.243535648254163e-05
    - 9.19777775028672e-05
    - 0.002108439388293255
    - 0.007915410610465138
    - 2.284160462373675e-06
  spo_GO:
    hidden_dims:
    - 99
    - 91
    - 103
    - 161
    - 225
    - 128
    - 255
    - 118
    - 113
    - 255
    - 100
    - 204
    lr_values:
    - 0.004004187767111486
    - 0.000993549677376645
    - 0.0009797275117599234
    - 2.0718057194320064e-05
    - 0.0005109102480500979
    - 4.590661039114639e-06
    - 0.000144842067896868
    - 0.0006215715195927046
    - 0.0007291911230603239
    - 0.009172546714689015
    - 2.254507450076466e-06
    - 0.002426367295063528
    dropout_values:
    - 0.7485136908258239
    - 0.49715247262485485
    - 0.49072605200443437
    - 0.7709407307069909
    - 0.3985583281620595
    - 0.5155358518906454
    - 0.6415071020633475
    - 0.42364021661517975
    - 0.603275210903751
    - 0.7520451290413288
    - 0.7942103846897423
    - 0.3096356762172921
    num_layers_values:
    - 3
    - 3
    - 1
    - 2
    - 1
    - 1
    - 1
    - 1
    - 1
    - 3
    - 3
    - 1
    weight_decay_values:
    - 1.9829623128384156e-06
    - 0.001005845321529227
    - 4.169682416024327e-06
    - 2.9144392552836642e-05
    - 1.4568229097824246e-06
    - 0.00018763354827875143
    - 2.184894755990559e-06
    - 0.0009440939833248185
    - 0.0037367463837606504
    - 0.0007797902373196692
    - 1.730447900213798e-05
    - 1.3414365128771287e-06
  gasch2_GO:
    hidden_dims:
    - 98
    - 56
    - 60
    - 71
    - 99
    - 79
    - 152
    - 105
    - 59
    - 106
    - 99
    - 70
    lr_values:
    - 0.00014712363884311096
    - 0.0009261705908935724
    - 0.008031677162792787
    - 3.0524381503857715e-05
    - 4.7490534690141576e-05
    - 0.006798215207681427
    - 0.004268267261410317
    - 0.001921930789369068
    - 0.0002161264817690757
    - 6.26529502364456e-05
    - 0.0019614343565925734
    - 4.644548806757818e-06
    dropout_values:
    - 0.5978690060574384
    - 0.3441279619412074
    - 0.5659453812536934
    - 0.5441072591568877
    - 0.5850279057032742
    - 0.41522072154270845
    - 0.6428437984100477
    - 0.763864957323905
    - 0.5989817616741139
    - 0.47814453023183145
    - 0.34093933150616673
    - 0.5798218859929012
    num_layers_values:
    - 3
    - 2
    - 1
    - 1
    - 2
    - 1
    - 2
    - 2
    - 1
    - 3
    - 2
    - 3
    weight_decay_values:
    - 9.049039891144442e-06
    - 4.304294203022999e-05
    - 0.0012869676235166036
    - 0.0004923953375314181
    - 0.0035642439227760968
    - 0.00020445606726589722
    - 2.3969650469474764e-06
    - 2.5032803063855622e-05
    - 1.6161199697474418e-05
    - 1.5182058333532373e-06
    - 0.002072296934285643
    - 2.938978497969489e-05
  cellcycle_FUN:
    hidden_dims:
    - 113
    - 120
    - 216
    - 153
    - 105
    - 121
    lr_values:
    - 0.001541314017423575
    - 0.0017016856411346856
    - 0.00149440265052631
    - 0.0015609927219782241
    - 2.2465608053196997e-06
    - 0.009181804396295965
    dropout_values:
    - 0.7094207921639194
    - 0.4690897287692786
    - 0.5083109338144302
    - 0.7034722547216256
    - 0.4068662469843937
    - 0.3163833547014781
    num_layers_values:
    - 1
    - 2
    - 2
    - 2
    - 1
    - 1
    weight_decay_values:
    - 0.0008723107978412028
    - 0.00022161912026809796
    - 2.9638027312182344e-06
    - 1.1003690802418857e-06
    - 2.5838423441020277e-05
    - 7.460150188818619e-05
  spo_FUN:
    hidden_dims:
    - 143
    - 203
    - 224
    - 179
    - 113
    - 228
    lr_values:
    - 0.001204920098605728
    - 0.002043324260368995
    - 0.0023217478361385506
    - 0.005247440068834808
    - 0.00466608117082463
    - 1.8486609145990984e-06
    dropout_values:
    - 0.7577475531837604
    - 0.5547666088129217
    - 0.4131017133024241
    - 0.4629862100328213
    - 0.47549034858946737
    - 0.31163545442264545
    num_layers_values:
    - 2
    - 2
    - 2
    - 2
    - 1
    - 2
    weight_decay_values:
    - 0.00024646076529222265
    - 4.2221263091948026e-06
    - 2.9497460328497426e-06
    - 1.2301383189322639e-05
    - 6.987444306388376e-06
    - 1.0891077500875083e-06
  seq_GO:
    hidden_dims:
    - 1349
    - 689
    - 657
    - 657
    - 1169
    - 872
    - 542
    - 1226
    - 615
    - 1471
    - 608
    - 659
    lr_values:
    - 3.63504806779836e-06
    - 0.0005006613051954613
    - 0.0003235564819470466
    - 6.547305070123571e-06
    - 0.00036388493136782886
    - 0.0009335520676549326
    - 5.175624021406398e-05
    - 0.0008157411083722959
    - 7.9950442414003e-06
    - 0.0003632533887726481
    - 0.001284753315149028
    - 0.00614466535175669
    dropout_values:
    - 0.3146300799951381
    - 0.3149408868404458
    - 0.5655289226905947
    - 0.33924628610397134
    - 0.6284179821314285
    - 0.6596808583156267
    - 0.35027191489981857
    - 0.5517216825489732
    - 0.49156035046591373
    - 0.41510270997253107
    - 0.3422509182774331
    - 0.6247235657499399
    num_layers_values:
    - 1
    - 1
    - 2
    - 1
    - 2
    - 1
    - 1
    - 1
    - 1
    - 1
    - 2
    - 1
    weight_decay_values:
    - 2.3917644293914117e-05
    - 6.210831599196901e-06
    - 9.249774450418514e-06
    - 0.005118042643389797
    - 5.6683625635603145e-06
    - 3.879135592968947e-05
    - 1.0495849451893025e-06
    - 0.002180519838551942
    - 0.001084356483464412
    - 9.727983269526494e-05
    - 0.0002960696142794555
    - 0.0020427607932010203
  gasch1_GO:
    hidden_dims:
    - 451
    - 306
    - 448
    - 173
    - 345
    - 246
    - 282
    - 342
    - 178
    - 377
    - 275
    - 226
    lr_values:
    - 2.862592961881182e-05
    - 0.00368606265822709
    - 0.00014170463320489543
    - 0.009692444989201634
    - 0.000645762568798969
    - 0.000321938690380098
    - 0.0001817985621064622
    - 0.0002813429914762808
    - 6.682445525254838e-06
    - 7.569334196722513e-06
    - 0.0012596010776636923
    - 1.9034428850345373e-05
    dropout_values:
    - 0.45120029544163076
    - 0.470010120751802
    - 0.4599881216943667
    - 0.34781486968602876
    - 0.7004749918651512
    - 0.32534757120587066
    - 0.7612745327204016
    - 0.4368643252493659
    - 0.43693327098000406
    - 0.33537688183995507
    - 0.6222674643252057
    - 0.36877107411379334
    num_layers_values:
    - 1
    - 1
    - 2
    - 2
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 3
    - 3
    weight_decay_values:
    - 0.001109491979308183
    - 0.005544014442240732
    - 0.0016512204556221077
    - 8.494972578760517e-06
    - 1.9733654899753738e-06
    - 7.5545371683937615e-06
    - 9.522110671715335e-05
    - 0.001182813995855044
    - 1.7828271210667967e-05
    - 9.01389336766496e-06
    - 2.8209379324176467e-05
    - 9.607188523929981e-05
  eisen_FUN:
    hidden_dims:
    - 184
    - 191
    - 164
    - 168
    - 126
    - 154
    lr_values:
    - 0.000485809484406076
    - 0.000141473011881943
    - 0.0047086494380709195
    - 0.009134827781615154
    - 5.584923276316496e-06
    - 0.0017672314265644296
    dropout_values:
    - 0.7590138069820841
    - 0.3630662775753951
    - 0.6584140474646869
    - 0.4151932107876353
    - 0.34376471915211826
    - 0.35460296787918266
    num_layers_values:
    - 1
    - 2
    - 2
    - 2
    - 1
    - 3
    weight_decay_values:
    - 0.002514352847749315
    - 8.053606442983053e-06
    - 8.66359738271223e-06
    - 3.775826895983162e-05
    - 9.546580307947481e-05
    - 2.5154371795360973e-06
  gasch1_FUN:
    hidden_dims:
    - 235
    - 340
    - 503
    - 304
    - 223
    - 514
    lr_values:
    - 0.00037494339713301574
    - 2.8231028955472248e-05
    - 0.0005437307974371547
    - 0.0033166801463249966
    - 0.009347126494266562
    - 0.0007415736930790839
    dropout_values:
    - 0.351160284459989
    - 0.4350462986031751
    - 0.46062462645214636
    - 0.7288365071853118
    - 0.3875610211527622
    - 0.32661314863226093
    num_layers_values:
    - 2
    - 2
    - 2
    - 2
    - 1
    - 1
    weight_decay_values:
    - 0.001918889673553552
    - 6.507838914966312e-06
    - 2.3333137710835596e-05
    - 1.1080767043983206e-05
    - 2.9499762600025313e-05
    - 1.1376379257233409e-05
  derisi_GO:
    hidden_dims:
    - 188
    - 144
    - 140
    - 118
    - 120
    - 110
    - 81
    - 97
    - 99
    - 180
    - 113
    - 187
    lr_values:
    - 4.410157602820844e-05
    - 3.686123282791643e-05
    - 0.0005509022296018059
    - 0.0006665748930566795
    - 0.0001656190168678033
    - 4.3663881400942485e-05
    - 0.0015103103297622062
    - 0.00031310623928687683
    - 0.00016135652008954088
    - 0.0014069962467239815
    - 1.6061715422999967e-06
    - 0.00010587478708622527
    dropout_values:
    - 0.761010191686916
    - 0.39712451187381664
    - 0.3463976774798306
    - 0.5252451154551537
    - 0.7193373318203241
    - 0.4908195269073206
    - 0.5413248326827782
    - 0.5102509257687191
    - 0.4062967306422557
    - 0.6391493431961983
    - 0.35659620269610814
    - 0.3052622134748653
    num_layers_values:
    - 3
    - 1
    - 1
    - 2
    - 3
    - 3
    - 1
    - 2
    - 2
    - 3
    - 1
    - 1
    weight_decay_values:
    - 0.0003186801795405554
    - 0.008607460543217253
    - 7.264999625059618e-05
    - 0.00010185642493236745
    - 0.0002587548793095443
    - 3.814706975620973e-05
    - 2.1965297224506787e-05
    - 3.1288647922501657e-06
    - 0.000755637105456791
    - 0.008611223978279875
    - 0.0017118670254691259
    - 0.00011421804953351186
  expr_FUN:
    hidden_dims:
    - 1345
    - 1167
    - 921
    - 568
    - 1360
    - 617
    lr_values:
    - 2.309155900717347e-06
    - 2.9968177387726874e-05
    - 4.751950318889048e-05
    - 1.6674951292418645e-05
    - 0.0019349039183021196
    - 7.823718399050946e-05
    dropout_values:
    - 0.3927782949569017
    - 0.3491748009980393
    - 0.6967993779511499
    - 0.47692375081090693
    - 0.6997847092024924
    - 0.7378395368109798
    num_layers_values:
    - 1
    - 1
    - 1
    - 1
    - 1
    - 2
    weight_decay_values:
    - 3.912886582953039e-06
    - 1.0426480347218373e-05
    - 3.6045849950160164e-05
    - 2.0573238093352002e-06
    - 0.00017055879401222477
    - 0.0001701865452855294
  gasch2_FUN:
    hidden_dims:
    - 78
    - 107
    - 65
    - 141
    - 88
    - 136
    lr_values:
    - 0.0019975703131340818
    - 0.0006380176850315875
    - 0.004374420047022926
    - 0.0034498076591270056
    - 1.0884359558899448e-06
    - 8.663234291453117e-06
    dropout_values:
    - 0.5268591572370462
    - 0.37106319334112947
    - 0.36204106874996544
    - 0.402768951993847
    - 0.3188955462837347
    - 0.41237305072909997
    num_layers_values:
    - 1
    - 2
    - 2
    - 2
    - 1
    - 3
    weight_decay_values:
    - 0.0006529445261141656
    - 3.2855312760747575e-06
    - 1.0050324494166777e-06
    - 2.725911673431021e-06
    - 2.8077802786249795e-05
    - 6.516580583346557e-06
  seq_FUN:
    hidden_dims:
    - 866
    - 855
    - 1570
    - 646
    - 542
    - 888
    lr_values:
    - 0.0002322183965991819
    - 0.0028267063030836983
    - 0.002667031978962203
    - 0.002762577996069365
    - 0.0019323644615973326
    - 3.866245946893665e-06
    dropout_values:
    - 0.6616651602301329
    - 0.45949619661687524
    - 0.3654199028258798
    - 0.6136826561130359
    - 0.3092827554643257
    - 0.3591445736030631
    num_layers_values:
    - 1
    - 2
    - 1
    - 1
    - 1
    - 1
    weight_decay_values:
    - 2.8359015926071173e-06
    - 8.016551305853878e-06
    - 0.00012301256913756488
    - 1.061632038558717e-05
    - 1.5607210841835122e-05
    - 5.261049430080029e-06

