datasets_params:
  derisi_FUN:
    hidden_dims:
    - 85
    - 63
    - 163
    - 82
    - 68
    - 89
    lr_values:
    - 2.10573521563438e-06
    - 1.24881585210531e-06
    - 1.0005648638797017e-06
    - 1.1421947730369764e-06
    - 1.0490525730983156e-06
    - 1.1545028966168291e-06
    dropout_values:
    - 0.7215954062431253
    - 0.3095510476713859
    - 0.3900909187773646
    - 0.5797756848088339
    - 0.5936389152926083
    - 0.6176596833863086
    num_layers_values:
    - 3
    - 1
    - 2
    - 2
    - 2
    - 2
    weight_decay_values:
    - 0.009949033084555636
    - 0.0004838318261815035
    - 0.0009819313123480772
    - 3.557739682876921e-05
    - 2.9555281186913432e-05
    - 0.0047905539821970185
  cellcycle_GO:
    hidden_dims:
    - 88
    - 119
    - 108
    - 304
    - 304
    - 424
    - 248
    - 402
    - 64
    - 268
    - 191
    - 64
    lr_values:
    - 1.1324841712528832e-06
    - 1.1207594352899598e-06
    - 1.7799255547836866e-06
    - 0.00012021725200202623
    - 0.00033616875019977976
    - 0.0003253919325483853
    - 0.0004058901580188073
    - 0.0008890283693445439
    - 1.649085150712473e-06
    - 0.0006604110612303427
    - 1.0244564440956921e-06
    - 1.2043608147573199e-06
    dropout_values:
    - 0.4175849475994753
    - 0.5498698456925137
    - 0.35479630320740074
    - 0.41947262537833613
    - 0.6500302470760554
    - 0.40272635253811767
    - 0.3941925541193297
    - 0.46378383449545446
    - 0.6748027051146338
    - 0.5500606784561465
    - 0.44546959763083405
    - 0.5329036604202667
    num_layers_values:
    - 3
    - 3
    - 2
    - 3
    - 2
    - 2
    - 1
    - 3
    - 2
    - 3
    - 2
    - 3
    weight_decay_values:
    - 3.530604979233372e-06
    - 0.00946604524698273
    - 0.00018604695114942375
    - 4.04466644096268e-05
    - 7.709342586825177e-05
    - 2.167554851919081e-06
    - 6.902977855600043e-06
    - 0.0002923694054818973
    - 0.009042291164366483
    - 0.0007258963258258184
    - 0.00014289774429477467
    - 0.00021192798117943305
  expr_GO:
    hidden_dims:
    - 2209
    - 650
    - 813
    - 890
    - 1067
    - 2148
    - 1342
    - 936
    - 883
    - 1727
    - 2007
    - 1427
    lr_values:
    - 0.0002827457526845376
    - 1.9547264982994417e-06
    - 0.000969286476983962
    - 4.226688296781053e-05
    - 4.5059994138730454e-05
    - 0.0009878400294120267
    - 0.0005353588276213192
    - 0.0002988738300709054
    - 0.0006414074295743398
    - 0.0009393845353111744
    - 0.00047996699638795925
    - 1.029663184124495e-06
    dropout_values:
    - 0.4214800154852704
    - 0.32524824231588606
    - 0.6521565019388367
    - 0.3598913262584258
    - 0.7680963456574383
    - 0.534722767855512
    - 0.6568711070637178
    - 0.35100752067507135
    - 0.3441097654412318
    - 0.36162279167931427
    - 0.5129387484856629
    - 0.31158918744479336
    num_layers_values:
    - 2
    - 3
    - 3
    - 3
    - 2
    - 2
    - 2
    - 3
    - 2
    - 2
    - 2
    - 2
    weight_decay_values:
    - 1.375159043585569e-06
    - 0.007686998445876798
    - 9.285676281228958e-06
    - 3.2779212569664235e-05
    - 1.3175534449353609e-05
    - 1.67449544935308e-05
    - 1.1182920989603582e-06
    - 5.702471760054384e-06
    - 2.2967963760844515e-06
    - 1.0450929342525568e-06
    - 1.0093585585436105e-05
    - 0.009980224585884944
  eisen_GO:
    hidden_dims:
    - 90
    - 85
    - 208
    - 127
    - 162
    - 131
    - 265
    - 177
    - 135
    - 100
    - 167
    lr_values:
    - 1.0188944140455341e-06
    - 1.6410511013867002e-06
    - 2.0620350437177288e-06
    - 2.001064712010464e-06
    - 1.0542842015510618e-06
    - 1.2109978845406026e-06
    - 0.00023758206291618362
    - 0.0007993075822637089
    - 0.0006629646108415332
    - 1.1631053113241667e-06
    - 1.698251455734375e-06
    dropout_values:
    - 0.7963812578106555
    - 0.519731063220033
    - 0.49969737940650777
    - 0.7294963112915093
    - 0.7990607343759977
    - 0.42850972395975795
    - 0.3723719683251926
    - 0.6172415789070479
    - 0.3074407458859128
    - 0.4171801482308659
    - 0.3059591612620124
    num_layers_values:
    - 3
    - 1
    - 3
    - 3
    - 2
    - 2
    - 1
    - 2
    - 3
    - 2
    - 1
    weight_decay_values:
    - 0.009654437204183847
    - 0.002127641327116301
    - 0.007872049110114021
    - 2.2551686922143853e-06
    - 0.009453197249911602
    - 0.009101863416862406
    - 1.1885072531121068e-05
    - 0.0007533634983195863
    - 0.0002107698346136703
    - 0.00012407198078676068
    - 1.5327930952694583e-06
  spo_GO:
    hidden_dims:
    - 86
    - 119
    - 167
    - 109
    - 201
    - 145
    - 251
    - 311
    - 127
    - 199
    - 86
    - 102
    lr_values:
    - 1.1388162521719103e-06
    - 1.5856737138430847e-06
    - 0.0006544351338241224
    - 1.0239958137856612e-06
    - 0.0006372600734879117
    - 2.305079389952042e-06
    - 0.0009986362068694278
    - 0.000987811967289523
    - 1.0077783467017754e-06
    - 0.00043045082840874826
    - 0.0009339535209589158
    - 1.024465838649727e-06
    dropout_values:
    - 0.6269109191885408
    - 0.3254871931897871
    - 0.7654324783812694
    - 0.38617359073834123
    - 0.6214976463919726
    - 0.5406718794218471
    - 0.5501733483830105
    - 0.4336923101932684
    - 0.3058408798309765
    - 0.31963013835670895
    - 0.39238200542411583
    - 0.7080200431086288
    num_layers_values:
    - 2
    - 1
    - 2
    - 3
    - 2
    - 2
    - 3
    - 3
    - 3
    - 2
    - 3
    - 3
    weight_decay_values:
    - 1.4137657272546657e-06
    - 0.004507473632421468
    - 3.458218436020352e-05
    - 0.009682717122008277
    - 8.53013014283891e-06
    - 0.009508204891644435
    - 3.4469825536777655e-05
    - 3.811601630742973e-06
    - 1.0897555797377719e-06
    - 1.0962076741979477e-06
    - 2.4900362491963125e-05
    - 0.0022297879782023056
  gasch2_GO:
    hidden_dims:
    - 76
    - 74
    - 53
    - 54
    - 148
    - 66
    - 53
    - 163
    - 66
    - 65
    - 74
    - 58
    lr_values:
    - 1.122395843820161e-06
    - 1.7407252453222017e-06
    - 1.4070393345561915e-06
    - 1.0050721697852775e-06
    - 1.0078037110099235e-06
    - 3.87475902419813e-06
    - 1.061146888068688e-06
    - 0.00047924905007535424
    - 1.7690899268857593e-06
    - 1.6157603402920504e-06
    - 0.00044680018610953356
    - 1.0670755622391176e-06
    dropout_values:
    - 0.4168243296959191
    - 0.663852807177017
    - 0.7778037725053347
    - 0.3745704300269772
    - 0.3732128648776265
    - 0.7710118540670026
    - 0.7670424781314412
    - 0.3478403927251982
    - 0.3169541438316502
    - 0.3578498066883892
    - 0.3293474752550356
    - 0.5845535855389757
    num_layers_values:
    - 2
    - 2
    - 3
    - 2
    - 2
    - 2
    - 3
    - 1
    - 2
    - 3
    - 3
    - 3
    weight_decay_values:
    - 0.0026067813652833403
    - 0.00958277154768888
    - 4.013098534935146e-06
    - 0.00016129538755328386
    - 0.007913414986504549
    - 0.00854612661540902
    - 1.0765839935025354e-06
    - 1.631739241831203e-05
    - 0.009183413397024802
    - 3.5628950094127933e-06
    - 1.5284453793845185e-06
    - 0.004123460651173287
  cellcycle_FUN:
    hidden_dims:
    - 113
    - 78
    - 77
    - 77
    - 93
    - 87
    lr_values:
    - 1.918722552604185e-06
    - 1.2717330815416245e-06
    - 1.0764437665446751e-06
    - 1.1192752763992434e-06
    - 1.6696774376439353e-06
    - 1.0700062933755661e-06
    dropout_values:
    - 0.7779704483822839
    - 0.7491032769371143
    - 0.7739834333120438
    - 0.32509020569668384
    - 0.30064349714011795
    - 0.7215185590583982
    num_layers_values:
    - 3
    - 2
    - 1
    - 2
    - 3
    - 1
    weight_decay_values:
    - 8.131284567870967e-06
    - 0.009035849727360679
    - 1.3341121492605331e-06
    - 0.00021123769330444226
    - 0.004457002062225091
    - 4.411543948234665e-05
  spo_FUN:
    hidden_dims:
    - 88
    - 151
    - 91
    - 316
    - 162
    - 148
    lr_values:
    - 1.1176480694912241e-06
    - 1.0515946219287565e-06
    - 1.1358397829999176e-06
    - 1.025713279522085e-06
    - 1.0076495300871739e-06
    - 1.0634283477297213e-06
    dropout_values:
    - 0.7916317697751499
    - 0.769900503964304
    - 0.3023364518525025
    - 0.7988444322261959
    - 0.42480151952689954
    - 0.5161404740980348
    num_layers_values:
    - 2
    - 3
    - 1
    - 3
    - 3
    - 3
    weight_decay_values:
    - 6.557505995302106e-06
    - 0.009978206650150563
    - 0.00905233880292915
    - 0.00880676882132777
    - 0.0005287609615822788
    - 2.839223360610923e-05
  seq_GO:
    hidden_dims:
    - 554
    - 1185
    - 1415
    - 1782
    - 703
    - 1122
    - 1250
    - 1976
    - 1508
    - 1527
    - 628
    - 676
    lr_values:
    - 0.00047497848764004405
    - 4.9020757385802114e-05
    - 0.0007247420152465175
    - 1.0883229608049607e-06
    - 2.1261291080136317e-06
    - 0.0009429899405368394
    - 0.0005648595482430355
    - 0.0009453874115819904
    - 0.000601112823583027
    - 0.0004186940181338285
    - 4.814621857115667e-06
    - 1.0189592831566593e-06
    dropout_values:
    - 0.40085312182610117
    - 0.37079767081966697
    - 0.4229166276017435
    - 0.7973734860969974
    - 0.6817529888305128
    - 0.4610599346804856
    - 0.3692692340798749
    - 0.3900388520181024
    - 0.544128154580492
    - 0.5462988102002271
    - 0.39661791577101857
    - 0.624772894084375
    num_layers_values:
    - 2
    - 3
    - 3
    - 1
    - 1
    - 2
    - 3
    - 3
    - 3
    - 3
    - 3
    - 1
    weight_decay_values:
    - 1.3416255486468998e-05
    - 2.4459671838666162e-05
    - 1.957962414636699e-06
    - 0.0005067476771662018
    - 0.009772377387454878
    - 2.3527769357172353e-06
    - 7.628591131570575e-06
    - 6.552614948134703e-05
    - 1.9701165093797406e-06
    - 1.5866993197066978e-06
    - 3.5248204917740827e-06
    - 1.6279344724386465e-05
  gasch1_GO:
    hidden_dims:
    - 208
    - 645
    - 533
    - 249
    - 436
    - 396
    - 190
    - 680
    - 310
    - 280
    - 191
    - 629
    lr_values:
    - 0.0001676917970600677
    - 1.1407486030758645e-06
    - 0.0006980011945820195
    - 1.0760210423842508e-06
    - 3.7026080963314674e-05
    - 1.5404908087506815e-06
    - 0.00042917852429097517
    - 0.00035830501073251455
    - 0.0006598583629211339
    - 0.0006178353976890458
    - 0.0004871415431123634
    - 1.4840289683457721e-06
    dropout_values:
    - 0.38602648560381314
    - 0.300665140626862
    - 0.33809941444687164
    - 0.4667989556262179
    - 0.34865794839798664
    - 0.3036336013720862
    - 0.41871536314255575
    - 0.31749605260945524
    - 0.3255174541669935
    - 0.7077388970532144
    - 0.30469350238536075
    - 0.6257205982704941
    num_layers_values:
    - 1
    - 3
    - 3
    - 1
    - 2
    - 3
    - 1
    - 2
    - 3
    - 2
    - 2
    - 1
    weight_decay_values:
    - 0.00010879534100176452
    - 0.008237364085015764
    - 3.922711189489526e-05
    - 3.6707573349250915e-05
    - 2.6678178086568837e-06
    - 0.007731152815760641
    - 1.2839975053372289e-05
    - 8.37370519850213e-06
    - 0.00042620551720249977
    - 0.003673352624662411
    - 1.8721423760125041e-06
    - 0.009500790923469797
  eisen_FUN:
    hidden_dims:
    - 124
    - 80
    - 90
    - 143
    - 119
    - 113
    lr_values:
    - 1.2342449010037351e-06
    - 1.3567743140739143e-06
    - 1.8474848631699543e-06
    - 1.0438232512319399e-06
    - 1.024864541455874e-06
    - 1.3247129825967335e-06
    dropout_values:
    - 0.7975741784950823
    - 0.39229494385257224
    - 0.5579507556364234
    - 0.675708100927612
    - 0.54438132744198
    - 0.4874973522391197
    num_layers_values:
    - 3
    - 1
    - 3
    - 3
    - 2
    - 2
    weight_decay_values:
    - 0.0024218513361029394
    - 2.6292647565957573e-06
    - 0.007985658362977658
    - 0.003255396986790634
    - 3.0487725279163523e-06
    - 0.0019776533498230913
  gasch1_FUN:
    hidden_dims:
    - 198
    - 230
    - 258
    - 418
    - 572
    - 434
    lr_values:
    - 1.0214753149385306e-06
    - 1.0189902712230084e-06
    - 1.0750336810626639e-06
    - 0.0004557255122022105
    - 1.076240169979616e-06
    - 1.0432828090849644e-06
    dropout_values:
    - 0.721023565167005
    - 0.7898475435378212
    - 0.517475793726239
    - 0.31326387723032645
    - 0.45422258322559256
    - 0.7970557315688764
    num_layers_values:
    - 3
    - 3
    - 3
    - 1
    - 1
    - 1
    weight_decay_values:
    - 1.256012179235673e-06
    - 9.890677625079316e-06
    - 0.002644701866580066
    - 0.007981111265395928
    - 0.008566959795796499
    - 4.91589592729306e-06
  derisi_GO:
    hidden_dims:
    - 69
    - 63
    - 104
    - 63
    - 65
    - 88
    - 66
    - 100
    - 128
    - 84
    - 80
    - 66
    lr_values:
    - 1.5162294490462497e-06
    - 1.2849730410072132e-05
    - 0.0007562514120122515
    - 1.2232476877054684e-06
    - 1.0055817049634026e-06
    - 1.075241013167154e-06
    - 1.3705475227569813e-06
    - 1.0127523018653496e-06
    - 1.8869749172707099e-06
    - 1.0021665455083866e-06
    - 1.0411598314730215e-06
    - 1.8561735034902576e-06
    dropout_values:
    - 0.6760073251628763
    - 0.4622206799387573
    - 0.46354247365939366
    - 0.6031991846002889
    - 0.6107093642656969
    - 0.30157131750782895
    - 0.3388493522202102
    - 0.5107668621812533
    - 0.7913953755041533
    - 0.4574033600635128
    - 0.7481034334330506
    - 0.3991012274771719
    num_layers_values:
    - 3
    - 3
    - 2
    - 1
    - 2
    - 1
    - 2
    - 1
    - 3
    - 1
    - 1
    - 1
    weight_decay_values:
    - 0.00036824633956529637
    - 0.008805083541138924
    - 6.345369348696853e-06
    - 0.009115983567071759
    - 0.00969509098064115
    - 0.009894977241944233
    - 0.0020359147940212075
    - 3.150282157271637e-05
    - 0.009456373339136459
    - 1.242433380088211e-05
    - 0.0018134098220989063
    - 0.003298254785573404
  expr_FUN:
    hidden_dims:
    - 1001
    - 1203
    - 1807
    - 2128
    - 1767
    - 1349
    lr_values:
    - 0.0006056854963399784
    - 2.139937961933416e-06
    - 1.7179232169429275e-06
    - 1.1070160226345704e-06
    - 5.025971287197845e-06
    - 8.561807686788372e-06
    dropout_values:
    - 0.5988209168818798
    - 0.4579679291904173
    - 0.4253092073270299
    - 0.7750492394404108
    - 0.3853610406075172
    - 0.5033153562535354
    num_layers_values:
    - 2
    - 3
    - 1
    - 3
    - 1
    - 3
    weight_decay_values:
    - 0.00012983702408013366
    - 0.0010478737268500653
    - 0.008100071974087079
    - 1.9858054601841998e-05
    - 0.008155142721651196
    - 0.00033445907183558436
  gasch2_FUN:
    hidden_dims:
    - 90
    - 70
    - 65
    - 61
    - 83
    - 89
    lr_values:
    - 1.0312987136359967e-06
    - 1.0392552175813136e-06
    - 3.0054398695274527e-06
    - 1.0607588579238904e-06
    - 1.0465060152212185e-06
    - 1.015330087277162e-06
    dropout_values:
    - 0.574491688022746
    - 0.4728215583478599
    - 0.7242361719891609
    - 0.33501370682555337
    - 0.5096558039236276
    - 0.5322732257390544
    num_layers_values:
    - 3
    - 3
    - 2
    - 3
    - 3
    - 3
    weight_decay_values:
    - 0.009110968298361239
    - 0.0010468835728102677
    - 0.009722613370290708
    - 0.0019870154388598273
    - 0.006268183971418285
    - 0.0009642374218858466
  seq_FUN:
    hidden_dims:
    - 740
    - 709
    - 855
    - 1740
    - 1242
    - 534
    lr_values:
    - 8.046550369520768e-05
    - 1.8596011419129215e-06
    - 1.295576804911046e-06
    - 1.0202967940008962e-06
    - 2.292026630586744e-06
    - 1.0959887813171084e-06
    dropout_values:
    - 0.5599006275879588
    - 0.6733809713311038
    - 0.4808995538099824
    - 0.5427589632572812
    - 0.33888497584040245
    - 0.5779339706204479
    num_layers_values:
    - 3
    - 3
    - 1
    - 2
    - 1
    - 3
    weight_decay_values:
    - 3.158817586339835e-05
    - 0.0002155741203089501
    - 0.009392472227041357
    - 0.007864038041711478
    - 0.009905779447501286
    - 0.009508439536911337
