datasets_params:
  eisen_FUN:
    hidden_dims:
    - 325
    - 126
    - 223
    - 385
    - 218
    - 177
    lr_values:
    - 6.23643071353427e-05
    - 0.0001497370895266225
    - 0.0007360944955338711
    - 1.961874229527143e-05
    - 0.0004098141045540399
    - 0.0006011107968318561
    dropout_values:
    - 0.6411832612007732
    - 0.3665573598351759
    - 0.7155079035506919
    - 0.4427057025617215
    - 0.5713856784427411
    - 0.42619154455083363
    num_layers_values:
    - 2
    - 2
    - 2
    - 1
    - 2
    - 3
    weight_decay_values:
    - 0.00025233756096540937
    - 0.00024615275676886597
    - 1.6386678171225996e-05
    - 8.388017155735756e-05
    - 0.00046388335018287527
    - 0.0047242600535158845
  seq_FUN:
    hidden_dims:
    - 149
    - 112
    - 397
    - 104
    - 450
    - 230
    lr_values:
    - 2.1214214016638487e-06
    - 1.2609927836905842e-05
    - 2.104060195953815e-05
    - 0.00094708520487657
    - 4.387579799046166e-05
    - 2.7085393149549587e-05
    dropout_values:
    - 0.4844986697567543
    - 0.3669185742327118
    - 0.4258456683648857
    - 0.6720765268528258
    - 0.5194385070194559
    - 0.5705583802971624
    num_layers_values:
    - 1
    - 1
    - 3
    - 3
    - 1
    - 3
    weight_decay_values:
    - 1.15721186418496e-06
    - 8.353713571458758e-05
    - 0.00012090762980111457
    - 5.482680091413e-06
    - 2.248567686255206e-05
    - 0.002951680974240372
  gasch2_GO:
    hidden_dims:
    - 144
    - 275
    - 378
    - 354
    - 206
    - 282
    - 100
    - 495
    - 444
    - 395
    - 253
    - 386
    - 496
    lr_values:
    - 0.0003635830711594725
    - 0.00023786240687808646
    - 0.00029842049540727866
    - 0.0001576194214478213
    - 0.0004742372263447847
    - 0.0006027369711660779
    - 0.0009839119242082582
    - 0.00022916419204322536
    - 0.0007932838708177884
    - 0.00046463145497492787
    - 0.0008502687861622132
    - 0.0002919210973736928
    - 0.000554432829428732
    dropout_values:
    - 0.314098343141374
    - 0.30294290036314087
    - 0.7972418542359877
    - 0.3710781537565036
    - 0.465399706734693
    - 0.5207557884897134
    - 0.7539443424124247
    - 0.36193340141550767
    - 0.4182786531802149
    - 0.41826831960841215
    - 0.5081693523124953
    - 0.43242724568041535
    - 0.47616614555070147
    num_layers_values:
    - 3
    - 3
    - 1
    - 2
    - 3
    - 3
    - 2
    - 3
    - 2
    - 3
    - 1
    - 1
    - 3
    weight_decay_values:
    - 7.063630997640411e-06
    - 1.002097558252089e-06
    - 0.00013553094066600177
    - 0.00014120638041058428
    - 4.866086299615155e-06
    - 1.2316029600138396e-06
    - 0.00020488923292680296
    - 2.8771910422579027e-05
    - 9.248300894094725e-05
    - 4.170965644869981e-05
    - 6.5770042621107e-05
    - 4.919192609134611e-06
    - 4.679493640198599e-06
  gasch1_FUN:
    hidden_dims:
    - 482
    - 361
    - 226
    - 216
    - 116
    - 65
    lr_values:
    - 1.2693655199564903e-05
    - 4.464992393937789e-06
    - 0.0001821340077235913
    - 0.00042934620297656697
    - 0.00010844472685940279
    - 0.00012940432190898955
    dropout_values:
    - 0.5646018431380266
    - 0.3843000240052071
    - 0.7310929878668231
    - 0.5284683518146936
    - 0.4102545699080932
    - 0.46513181489506433
    num_layers_values:
    - 1
    - 1
    - 1
    - 1
    - 2
    - 3
    weight_decay_values:
    - 0.002769171670452383
    - 1.0639266957951343e-05
    - 1.644173808519384e-05
    - 6.218246644924561e-05
    - 0.00023281670579033067
    - 0.0054921949014106975
  cellcycle_FUN:
    hidden_dims:
    - 247
    - 343
    - 208
    - 258
    - 166
    - 96
    lr_values:
    - 0.00013720279301491722
    - 7.193380355835768e-05
    - 0.0005027122161437187
    - 0.000139281299062342
    - 0.00023834566365139935
    - 0.0004010409642910506
    dropout_values:
    - 0.6297340106538236
    - 0.649224823170305
    - 0.5226586599946695
    - 0.6733087456226523
    - 0.42057238257949
    - 0.3070508222561699
    num_layers_values:
    - 2
    - 2
    - 3
    - 2
    - 2
    - 1
    weight_decay_values:
    - 7.029214653788005e-05
    - 0.0002277380382597882
    - 1.0002685458629232e-06
    - 7.399186502389402e-05
    - 0.0006701649870431829
    - 0.0007616845484956434
  expr_FUN:
    hidden_dims:
    - 247
    - 414
    - 161
    - 239
    - 177
    - 207
    lr_values:
    - 2.0779992991806975e-06
    - 3.6392232418511506e-05
    - 1.528159050025254e-05
    - 0.0001251593110511188
    - 4.776022360466157e-05
    - 0.00032050086586960674
    dropout_values:
    - 0.5137659847751554
    - 0.4448397936449581
    - 0.5295529589179442
    - 0.5882461275752812
    - 0.3036833269687037
    - 0.40343559402072987
    num_layers_values:
    - 2
    - 1
    - 2
    - 2
    - 3
    - 2
    weight_decay_values:
    - 0.00016880839336694235
    - 1.813167362998593e-05
    - 2.3440466124325874e-06
    - 0.00028504316294160266
    - 0.0003012610257855658
    - 0.002743619339959904
  spo_GO:
    hidden_dims:
    - 87
    - 252
    - 72
    - 436
    - 482
    - 323
    - 229
    - 512
    - 85
    - 151
    - 378
    - 490
    - 174
    lr_values:
    - 0.0009016125387530451
    - 0.0009432460592248538
    - 0.0009682966322518223
    - 0.000433088637547764
    - 5.3818268366705945e-05
    - 0.0005300346327952001
    - 0.0003373254351380555
    - 0.0009906292927052995
    - 0.000999362935716895
    - 0.000453642885591061
    - 0.00019838908771487742
    - 0.00045392060775595187
    - 0.00011400876522474324
    dropout_values:
    - 0.7238397616077326
    - 0.7207971260281343
    - 0.5739510016933649
    - 0.7912169418493917
    - 0.30175328366869647
    - 0.6216718766834732
    - 0.38453385930133244
    - 0.33295472971000956
    - 0.3290217100092843
    - 0.665253534857083
    - 0.35997740334510175
    - 0.4622141825005134
    - 0.36124047109869317
    num_layers_values:
    - 3
    - 3
    - 3
    - 2
    - 3
    - 3
    - 2
    - 3
    - 3
    - 3
    - 2
    - 3
    - 3
    weight_decay_values:
    - 3.0915212411796226e-05
    - 3.947594934917493e-06
    - 1.1941634955369367e-06
    - 7.840241983717998e-05
    - 1.604489149600035e-05
    - 2.754448942210988e-05
    - 3.123186571737596e-05
    - 3.6808439206080634e-05
    - 3.306600980729387e-06
    - 0.00028200013224140367
    - 0.00017969115235926198
    - 0.0010874277648889935
    - 1.0735056608459716e-06
  eisen_GO:
    hidden_dims:
    - 85
    - 116
    - 398
    - 438
    - 310
    - 131
    - 237
    - 271
    - 410
    - 207
    - 489
    - 325
    lr_values:
    - 0.0009742317071141227
    - 0.0008916132880220945
    - 7.901623784517872e-05
    - 0.00018730497904670998
    - 0.00015393790162060306
    - 0.0006147971433288841
    - 0.0005088090388702174
    - 0.00022765618279143888
    - 0.0005497357727965929
    - 0.0002962219804177943
    - 0.0004322720410574327
    - 0.00012064647932484423
    dropout_values:
    - 0.7984077439183155
    - 0.3243785697084349
    - 0.487961847282608
    - 0.5328584904740291
    - 0.40712582131817926
    - 0.529375785579086
    - 0.6672510816875169
    - 0.3367985283197259
    - 0.4204434772465274
    - 0.36732493176045594
    - 0.6344315200857795
    - 0.3922487150718887
    num_layers_values:
    - 3
    - 3
    - 2
    - 1
    - 3
    - 2
    - 3
    - 2
    - 2
    - 2
    - 2
    - 3
    weight_decay_values:
    - 3.091724819123401e-05
    - 1.0488966673865478e-06
    - 1.4764566505775849e-05
    - 0.0003068035995317498
    - 3.8143207504566644e-06
    - 4.751302190078577e-06
    - 0.00013886166721710716
    - 8.670573125637657e-06
    - 5.043797909640335e-05
    - 2.141962678354477e-05
    - 0.000109363537657795
    - 1.028192039721635e-06
  derisi_FUN:
    hidden_dims:
    - 107
    - 85
    - 292
    - 457
    - 208
    - 335
    lr_values:
    - 5.789868614671973e-05
    - 0.0001288619329029982
    - 0.00013759941084418343
    - 4.929517860792887e-05
    - 0.00021265875577385643
    - 4.890743490219517e-05
    dropout_values:
    - 0.49946903056703956
    - 0.34004411394333767
    - 0.6095507499946694
    - 0.33659207966140936
    - 0.42153349173405213
    - 0.3428206199401252
    num_layers_values:
    - 2
    - 3
    - 3
    - 3
    - 2
    - 3
    weight_decay_values:
    - 1.466843773138637e-05
    - 1.3652311207683814e-06
    - 1.5129476690884931e-05
    - 3.550138770533951e-05
    - 0.00015428248870775354
    - 0.004966126904407273
  derisi_GO:
    hidden_dims:
    - 278
    - 181
    - 146
    - 255
    - 144
    - 328
    - 181
    - 408
    - 130
    - 415
    - 106
    - 245
    - 493
    lr_values:
    - 0.0005332146844459446
    - 0.0009566645360135937
    - 0.00020415304830357657
    - 0.0009297039296656925
    - 0.00040478331750837227
    - 0.00021325078987793864
    - 0.0006209750024254313
    - 0.00038987377354317027
    - 0.0005723070333424593
    - 0.0006317690789487275
    - 0.0007055214396878316
    - 0.0009895652275542682
    - 0.0008564016358542348
    dropout_values:
    - 0.32759331073539144
    - 0.4209177879693472
    - 0.41752632649867133
    - 0.4038938275023332
    - 0.3327023613168404
    - 0.4681147014721308
    - 0.3344471801751351
    - 0.45920193915964813
    - 0.4580710693887729
    - 0.39180658040763994
    - 0.5488090000337758
    - 0.5537443866780462
    - 0.30341398423140753
    num_layers_values:
    - 3
    - 3
    - 2
    - 2
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 3
    - 2
    - 3
    weight_decay_values:
    - 3.406795564081332e-06
    - 1.9199683848367715e-06
    - 0.0001479282130223358
    - 5.4658925062576845e-06
    - 2.5472596777199178e-06
    - 2.976908273197287e-05
    - 1.5918350926489967e-05
    - 1.8177294831069083e-05
    - 0.00022907899558804182
    - 0.00016037586860477045
    - 9.174657527414725e-05
    - 0.0009341838971113038
    - 1.0158636570377574e-06
  gasch2_FUN:
    hidden_dims:
    - 303
    - 134
    - 148
    - 128
    - 288
    - 98
    lr_values:
    - 0.00017948228450327097
    - 0.0003869364831890819
    - 0.00024878218424297034
    - 0.00044401129365611837
    - 0.0004807534327213356
    - 5.9637911527979336e-05
    dropout_values:
    - 0.33891413063076026
    - 0.5363582167089527
    - 0.42843956409914125
    - 0.4087320249222326
    - 0.7889275025160899
    - 0.6154321266210016
    num_layers_values:
    - 2
    - 2
    - 2
    - 2
    - 3
    - 1
    weight_decay_values:
    - 0.0016620169185904692
    - 9.05256372632621e-05
    - 6.280346275774067e-05
    - 0.00010257312603794654
    - 1.5007359046625016e-05
    - 0.0015883071601533296
  expr_GO:
    hidden_dims:
    - 126
    - 134
    - 186
    - 406
    - 292
    - 136
    - 124
    - 510
    - 317
    - 183
    - 437
    - 482
    - 100
    lr_values:
    - 0.0009234586130041077
    - 0.00024481743262407625
    - 5.1480138347039315e-06
    - 1.4023122939015634e-05
    - 0.00011667371738439649
    - 0.00018427448023730365
    - 0.0007350792499183427
    - 8.269113898784346e-05
    - 0.0003898218042680984
    - 0.0002700966713223291
    - 0.0001123553789361745
    - 8.274459959730931e-05
    - 0.00097145961155579
    dropout_values:
    - 0.6636728102938851
    - 0.6527791302140585
    - 0.4152642751161054
    - 0.6313418327236584
    - 0.37280521285059687
    - 0.3281918470411577
    - 0.5377465597355953
    - 0.38130497497967336
    - 0.7905698632821343
    - 0.3895833604949883
    - 0.5934836010369953
    - 0.3006865528929133
    - 0.6217593915614992
    num_layers_values:
    - 3
    - 3
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 1
    - 2
    - 3
    - 2
    - 3
    weight_decay_values:
    - 1.0290504894901217e-06
    - 2.5906362625535033e-06
    - 0.00012120596892878636
    - 1.539216230716671e-05
    - 3.4311291477947455e-05
    - 3.227797724048491e-05
    - 4.5081147242937885e-05
    - 1.7721831066407378e-05
    - 2.399661795776624e-05
    - 2.034876551993876e-06
    - 8.352893863537895e-05
    - 0.0003232255884284126
    - 4.232229804268989e-05
  cellcycle_GO:
    hidden_dims:
    - 180
    - 399
    - 368
    - 474
    - 223
    - 472
    - 309
    - 512
    - 429
    - 89
    - 65
    - 143
    - 149
    lr_values:
    - 0.0009963727095990992
    - 0.0003465310461155656
    - 7.298298954867895e-05
    - 0.0003380106377978717
    - 0.0003582743019740857
    - 0.000654741200596686
    - 0.0005867032015872111
    - 0.00054887142319717
    - 0.0006882149733552994
    - 0.0006608424286316187
    - 0.0009839673937327314
    - 0.00035171374236142106
    - 0.0009869290821578355
    dropout_values:
    - 0.30150290575926086
    - 0.6764319109981548
    - 0.7968951785347027
    - 0.5992381464270515
    - 0.4787683246983884
    - 0.7172337499787376
    - 0.41492667608617345
    - 0.6871134617564508
    - 0.4366278893530925
    - 0.5324455325748328
    - 0.6359693906393972
    - 0.604348155363139
    - 0.7436840044550995
    num_layers_values:
    - 3
    - 3
    - 1
    - 2
    - 3
    - 2
    - 2
    - 3
    - 3
    - 3
    - 3
    - 2
    - 2
    weight_decay_values:
    - 1.2539001091220943e-06
    - 5.032162929922031e-06
    - 0.0009701367207278768
    - 0.00024080342551278572
    - 1.2111762572996768e-05
    - 4.262032330870436e-05
    - 5.160879416717214e-05
    - 0.00029037381079613186
    - 0.00012030213069799929
    - 0.0005703534858379407
    - 0.001252160491583488
    - 0.0006534993169237375
    - 2.3564440420915303e-06
  seq_GO:
    hidden_dims:
    - 405
    - 465
    - 161
    - 87
    - 234
    - 381
    - 408
    - 506
    - 342
    - 429
    - 123
    - 402
    - 299
    lr_values:
    - 0.0004832466882241258
    - 0.0009914477631457483
    - 0.0004973588278462893
    - 0.0002201844766237552
    - 2.4318893911895704e-05
    - 0.0009625375047472809
    - 6.39585530778709e-05
    - 0.0009949788784282467
    - 0.00015790586178070134
    - 0.00038097344777225244
    - 0.0002457479164001078
    - 0.0003110590985069806
    - 0.0009971882476931307
    dropout_values:
    - 0.505949329660155
    - 0.3753991670398607
    - 0.7483723650147535
    - 0.3375042206550268
    - 0.35574138874779476
    - 0.7141981548643073
    - 0.37323585385025326
    - 0.551119268866869
    - 0.4986678117646866
    - 0.7329774366952503
    - 0.531359452501676
    - 0.45531982155749573
    - 0.35705235687576165
    num_layers_values:
    - 3
    - 3
    - 1
    - 1
    - 2
    - 2
    - 1
    - 2
    - 2
    - 3
    - 2
    - 3
    - 3
    weight_decay_values:
    - 2.7333640225648965e-06
    - 2.4930567787049186e-06
    - 0.001027464550541928
    - 1.4924350279797643e-05
    - 6.236278727848426e-05
    - 3.0844852442470003e-05
    - 7.201010961871175e-06
    - 1.2907254674102501e-05
    - 1.7180116061812743e-05
    - 0.00019486270217615302
    - 0.00014262592756336564
    - 0.0003161441949282497
    - 4.431431477908848e-06
  gasch1_GO:
    hidden_dims:
    - 504
    - 127
    - 429
    - 210
    - 128
    - 416
    - 234
    - 217
    - 311
    - 243
    - 408
    - 334
    - 210
    lr_values:
    - 0.0009754115432826456
    - 0.0005444778920703651
    - 5.799541379659604e-05
    - 0.0009068805665656319
    - 0.0005235714074926425
    - 0.00022250285228708083
    - 0.0009294182567688284
    - 0.0003777782328459612
    - 0.0004864260787379994
    - 0.0005591730760436395
    - 0.00010017809970157454
    - 0.00019810403836590198
    - 0.0001779304391424027
    dropout_values:
    - 0.3065287845311618
    - 0.4185528230246522
    - 0.6507179643051528
    - 0.7306023217199856
    - 0.5490691504377427
    - 0.6323876083043996
    - 0.4902489892693604
    - 0.3798698462214869
    - 0.7159263940559693
    - 0.5005530218362821
    - 0.35347684767208937
    - 0.5822432447787347
    - 0.36342008515250135
    num_layers_values:
    - 3
    - 3
    - 1
    - 1
    - 2
    - 2
    - 2
    - 2
    - 2
    - 3
    - 2
    - 2
    - 3
    weight_decay_values:
    - 4.310450125680548e-06
    - 1.164070063007412e-06
    - 5.473379650236648e-05
    - 6.801654248216755e-05
    - 2.1904494088344815e-05
    - 4.987285918590428e-05
    - 1.3064055397979264e-06
    - 1.951381437719912e-06
    - 4.663550987342368e-05
    - 0.00033905560079980617
    - 2.0290111478831155e-05
    - 4.354876816191538e-06
    - 1.3396831310955485e-06
  spo_FUN:
    hidden_dims:
    - 425
    - 132
    - 268
    - 293
    - 290
    - 334
    lr_values:
    - 0.0004957866916711276
    - 0.0005854591031551631
    - 0.00025194330721464047
    - 0.0007593583882684058
    - 0.00012467301550611788
    - 0.00015585145051170195
    dropout_values:
    - 0.7505780637692102
    - 0.4872795964936556
    - 0.31729483804762965
    - 0.7518354258138391
    - 0.4700885352343892
    - 0.3087605063566715
    num_layers_values:
    - 3
    - 2
    - 3
    - 2
    - 2
    - 2
    weight_decay_values:
    - 0.0007066142163787854
    - 5.395311334584087e-05
    - 9.968348507928811e-06
    - 6.834958198828157e-05
    - 4.1372286463237384e-06
    - 0.0007463726367803831
