datasets_params:
  cellcycle_GO:
    hidden_dims: [142, 350, 376, 72, 136, 153]
    lr_values: [0.0008535163586361489, 0.00020838943720646224, 0.00011632934642816514, 0.0003333768880179626, 0.00019155119242967724, 0.000009829667617536004]
    dropout_values: [0.6165530577112526, 0.431511720735488, 0.7549295391636867, 0.43637069205386275, 0.5647101400146175, 0.34947751279503464]
    num_layers_values: [1, 1, 1, 2, 1, 2]
    weight_decay_values: [0.002967491473222236, 0.00023288161624906444, 0.00010262227175129532, 0.000283159428536993, 0.00013560726386788324, 0.000009762636975906581]
  derisi_GO:
    hidden_dims: [...]
    lr_values: [...]
    dropout_values: [...]
    num_layers_values: [...]
    weight_decay_values: [...]
  eisen_GO:
    hidden_dims: [...]
    lr_values: [...]
    dropout_values: [...]
    num_layers_values: [...]
    weight_decay_values: [...]
  expr_GO:
    hidden_dims: [...]
    lr_values: [...]
    dropout_values: [...]
    num_layers_values: [...]
    weight_decay_values: [...]
  gasch1_GO:
    hidden_dims: [...]
    lr_values: [...]
    dropout_values: [...]
    num_layers_values: [...]
    weight_decay_values: [...]
  gasch2_GO:
    hidden_dims: [...]
    lr_values: [...]
    dropout_values: [...]
    num_layers_values: [...]
    weight_decay_values: [...]
  seq_GO:
    hidden_dims: [...]
    lr_values: [...]
    dropout_values: [...]
    num_layers_values: [...]
    weight_decay_values: [...]
  spo_GO:
    hidden_dims: [...]
    lr_values: [...]
    dropout_values: [...]
    num_layers_values: [...]
    weight_decay_values: [...]
  cellcycle_FUN:
    hidden_dims: [...]
    lr_values: [...]
    dropout_values: [...]
    num_layers_values: [...]
    weight_decay_values: [...]
  derisi_FUN:
    hidden_dims: [...]
    lr_values: [...]
    dropout_values: [...]
    num_layers_values: [...]
    weight_decay_values: [...]
  eisen_FUN:
    hidden_dims: [...]
    lr_values: [...]
    dropout_values: [...]
    num_layers_values: [...]
    weight_decay_values: [...]
  expr_FUN:
    hidden_dims: [...]
    lr_values: [...]
    dropout_values: [...]
    num_layers_values: [...]
    weight_decay_values: [...]
  gasch1_FUN:
    hidden_dims: [...]
    lr_values: [...]
    dropout_values: [...]
    num_layers_values: [...]
    weight_decay_values: [...]
  gasch2_FUN:
    hidden_dims: [...]
    lr_values: [...]
    dropout_values: [...]
    num_layers_values: [...]
    weight_decay_values: [...]
  seq_FUN:
    hidden_dims: [142, 350, 376, 72, 136, 153]
    lr_values: [0.0008535163586361489, 0.00020838943720646224, 0.00011632934642816514, 0.0003333768880179626, 0.00019155119242967724, 0.000009829667617536004]
    dropout_values: [0.6165530577112526, 0.431511720735488, 0.7549295391636867, 0.43637069205386275, 0.5647101400146175, 0.34947751279503464]
    num_layers_values: [1, 1, 1, 2, 1, 2]
    weight_decay_values: [0.002967491473222236, 0.00023288161624906444, 0.00010262227175129532, 0.000283159428536993, 0.00013560726386788324, 0.000009762636975906581]
  spo_FUN:
    hidden_dims: [...]
    lr_values: [...]
    dropout_values: [...]
    num_layers_values: [...]
    weight_decay_values: [...]