datasets_params:
  derisi_FUN:
    hidden_dims:
    - 151
    - 69
    - 186
    - 111
    - 180
    - 185
    lr_values:
    - 0.000966948948793251
    - 0.0017023145388849927
    - 0.0059180881263707266
    - 0.0014955151379876697
    - 0.0008383458659425232
    - 8.449023263251544e-06
    dropout_values:
    - 0.5147672879284397
    - 0.5102403786362207
    - 0.36706324193923034
    - 0.31642263203941073
    - 0.5888026612791595
    - 0.7087369624077865
    num_layers_values:
    - 2
    - 1
    - 2
    - 1
    - 1
    - 1
    weight_decay_values:
    - 4.313158607116592e-06
    - 0.0004244450326654299
    - 1.0611512577483932e-06
    - 1.1860067966373887e-06
    - 0.006158605166039836
    - 0.007019086882635842
  cellcycle_GO:
    hidden_dims:
    - - 201
      - 136
    - - 226
    - - 107
    - - 172
      - 108
    - - 94
      - 90
    - - 102
    - - 211
      - 141
      - 154
      - 103
      - 84
    - - 116
    - - 176
      - 111
    - - 204
    - - 110
    - - 171
      - 139
    lr_values:
    - 0.005782697475518524
    - 0.0022479136784899823
    - 0.0002664237007197918
    - 0.00013884530924063992
    - 3.8391829767291815e-05
    - 0.00844529562921056
    - 0.002624539485379512
    - 0.003364192585607739
    - 3.105556647768938e-05
    - 1.5853153980119662e-05
    - 1.129619283491613e-06
    - 0.0019481704579642977
    dropout_values:
    - 0.7023135880174195
    - 0.6711795259352769
    - 0.5642102133229793
    - 0.750010264467878
    - 0.3414901163607416
    - 0.519580412552857
    - 0.3886116464530791
    - 0.31767222069042544
    - 0.492724907835188
    - 0.4394206476133195
    - 0.4033177040893441
    - 0.5481391726620308
    num_layers_values:
    - 2
    - 1
    - 1
    - 2
    - 2
    - 1
    - 5
    - 1
    - 2
    - 1
    - 1
    - 2
    weight_decay_values:
    - 2.2179059682025458e-05
    - 2.4457108102318877e-06
    - 4.9592978717780806e-05
    - 0.0002856694665913656
    - 0.0007369511905048901
    - 1.1639174799171395e-06
    - 5.75321092666116e-05
    - 0.0008372138350890247
    - 1.7439069317055988e-05
    - 0.006435329511015869
    - 0.0020227016344100514
    - 1.9062012964251033e-06
  expr_GO:
    hidden_dims:
    - 1106
    - 1049
    - 974
    - 1424
    - 1530
    - 566
    - 1483
    - 1140
    - 570
    - 677
    - 1224
    - 1338
    lr_values:
    - 0.0005336803302756717
    - 6.847105576684053e-06
    - 0.001672456362593246
    - 1.8908974745983059e-06
    - 0.0003959545485293144
    - 0.0013752026104598186
    - 5.8897354646525955e-05
    - 0.0001395436179704141
    - 7.667321275027086e-06
    - 8.932382336023003e-06
    - 0.003288054838432412
    - 0.0005967956428582452
    dropout_values:
    - 0.5468332247391668
    - 0.4612663627283168
    - 0.6611922396438937
    - 0.6622376807629174
    - 0.5393941934323763
    - 0.5215203532470222
    - 0.4616530989334182
    - 0.3105879102509167
    - 0.4568512578944138
    - 0.4661282760890452
    - 0.36678565146042297
    - 0.33002261445528597
    num_layers_values:
    - 2
    - 3
    - 2
    - 2
    - 3
    - 2
    - 2
    - 1
    - 1
    - 1
    - 1
    - 1
    weight_decay_values:
    - 0.005956516018710569
    - 2.559642090152666e-06
    - 3.836942747469319e-05
    - 4.2533702481412986e-05
    - 8.265408695475642e-06
    - 0.0010804925700431671
    - 0.0014385419088660785
    - 0.00010966483998589818
    - 1.0180379153792234e-05
    - 0.002273822130473567
    - 0.0005069556050561941
    - 0.00012017371812831088
  eisen_GO:
    hidden_dims:
    - 83
    - 148
    - 166
    - 201
    - 85
    - 116
    - 106
    - 97
    - 231
    - 109
    - 125
    lr_values:
    - 0.007542958005038003
    - 6.847105576684053e-06
    - 9.885817165390822e-06
    - 1.8908974745983059e-06
    - 0.0038608699421558
    - 0.004119826805392098
    - 1.1180792739776067e-05
    - 0.003374159753535832
    - 0.00035896080417169193
    - 0.006365176404906979
    - 0.00045615560787626844
    dropout_values:
    - 0.323501164987186
    - 0.4612663627283168
    - 0.3909634953339157
    - 0.6622376807629174
    - 0.5841459004644107
    - 0.7545983621399663
    - 0.3412941278325297
    - 0.7280985296052709
    - 0.792459834747991
    - 0.7937560097474852
    - 0.3220363527856101
    num_layers_values:
    - 3
    - 3
    - 2
    - 2
    - 1
    - 2
    - 1
    - 1
    - 1
    - 1
    - 1
    weight_decay_values:
    - 0.0024198379631834807
    - 2.559642090152666e-06
    - 0.007059178772516602
    - 4.2533702481412986e-05
    - 0.0001400608779843278
    - 0.0009877669239056238
    - 1.6084017535714163e-05
    - 6.724278410701681e-05
    - 4.48557067854471e-06
    - 2.6523120569982373e-06
    - 0.005706303983788867
  spo_GO:
    hidden_dims:
    - 90
    - 252
    - 181
    - 218
    - 92
    - 127
    - 211
    - 105
    - 176
    - 116
    - 121
    - 95
    lr_values:
    - 0.0031878308768521113
    - 0.0009058458887563657
    - 9.885817165390822e-06
    - 1.8908974745983059e-06
    - 0.0038608699421558
    - 0.004119826805392098
    - 0.0031832345185377323
    - 0.003374159753535832
    - 0.00031039387967131095
    - 8.937765793453951e-06
    - 2.1578927861081668e-05
    - 0.003530556165935282
    dropout_values:
    - 0.5090589725334038
    - 0.4750638816572068
    - 0.3909634953339157
    - 0.6622376807629174
    - 0.5841459004644107
    - 0.7545983621399663
    - 0.3317118155136052
    - 0.7280985296052709
    - 0.5263246831197463
    - 0.4350985542339063
    - 0.4325361823751828
    - 0.3750936231021622
    num_layers_values:
    - 3
    - 3
    - 2
    - 2
    - 1
    - 2
    - 2
    - 1
    - 3
    - 1
    - 1
    - 1
    weight_decay_values:
    - 4.6353764231647666e-05
    - 0.0002626528266326433
    - 0.007059178772516602
    - 4.2533702481412986e-05
    - 0.0001400608779843278
    - 0.0009877669239056238
    - 2.2553979251875746e-06
    - 6.724278410701681e-05
    - 0.0001409048311109052
    - 0.000988901487512057
    - 0.0010054954083691307
    - 0.0003112996927804979
  gasch2_GO:
    hidden_dims:
    - 134
    - 97
    - 109
    - 132
    - 55
    - 76
    - 146
    - 104
    - 152
    - 72
    - 113
    - 124
    lr_values:
    - 0.0030784215760494694
    - 6.847105576684053e-06
    - 9.885817165390822e-06
    - 1.8908974745983059e-06
    - 0.0038608699421558
    - 0.004119826805392098
    - 0.0031832345185377323
    - 0.003684644581949731
    - 0.00035896080417169193
    - 0.006361510516064462
    - 0.003288054838432412
    - 0.0005967956428582452
    dropout_values:
    - 0.5913820035582498
    - 0.4612663627283168
    - 0.3909634953339157
    - 0.6622376807629174
    - 0.5841459004644107
    - 0.7545983621399663
    - 0.3317118155136052
    - 0.4299159417283323
    - 0.792459834747991
    - 0.7964656798661114
    - 0.36678565146042297
    - 0.33002261445528597
    num_layers_values:
    - 3
    - 3
    - 2
    - 2
    - 1
    - 2
    - 2
    - 1
    - 1
    - 1
    - 1
    - 1
    weight_decay_values:
    - 5.682585466873625e-05
    - 2.559642090152666e-06
    - 0.007059178772516602
    - 4.2533702481412986e-05
    - 0.0001400608779843278
    - 0.0009877669239056238
    - 2.2553979251875746e-06
    - 1.6490591384239207e-05
    - 4.48557067854471e-06
    - 1.313422471455989e-06
    - 0.0005069556050561941
    - 0.00012017371812831088
  cellcycle_FUN:
    hidden_dims:
    - 114
    - 124
    - 145
    - 136
    - 129
    - 226
    lr_values:
    - 0.0004645867951512481
    - 0.00338622624765405
    - 0.006471367240175249
    - 0.0014955151379876697
    - 0.002086189194485109
    - 8.449023263251544e-06
    dropout_values:
    - 0.4605568032990952
    - 0.34213672856600696
    - 0.5361824633592402
    - 0.31642263203941073
    - 0.6402413556679323
    - 0.7087369624077865
    num_layers_values:
    - 2
    - 3
    - 2
    - 1
    - 1
    - 1
    weight_decay_values:
    - 1.7414134181586206e-06
    - 3.8386036131893384e-05
    - 7.804166575000096e-06
    - 1.1860067966373887e-06
    - 0.00014786233970049892
    - 0.007019086882635842
  spo_FUN:
    hidden_dims:
    - 127
    - 258
    - 162
    - 204
    - 245
    - 252
    lr_values:
    - 0.0004645867951512481
    - 0.0018375979494334234
    - 0.006471367240175249
    - 0.0033269347431517334
    - 0.0008383458659425232
    - 8.449023263251544e-06
    dropout_values:
    - 0.4605568032990952
    - 0.7274610821733851
    - 0.5361824633592402
    - 0.7205502356507218
    - 0.5888026612791595
    - 0.7087369624077865
    num_layers_values:
    - 2
    - 3
    - 2
    - 1
    - 1
    - 1
    weight_decay_values:
    - 1.7414134181586206e-06
    - 3.5270738306820234e-05
    - 7.804166575000096e-06
    - 0.004110178345415376
    - 0.006158605166039836
    - 0.007019086882635842
  seq_GO:
    hidden_dims:
    - 539
    - 989
    - 1114
    - 1343
    - 1269
    - 1014
    - 645
    - 1075
    - 538
    - 713
    - 1395
    - 1261
    lr_values:
    - 7.402828040757734e-05
    - 6.847105576684053e-06
    - 9.885817165390822e-06
    - 1.8908974745983059e-06
    - 0.00041231239455389153
    - 0.0014334748434454722
    - 0.0013025115520289724
    - 0.0001395436179704141
    - 7.667321275027086e-06
    - 8.937765793453951e-06
    - 0.00497339446958678
    - 0.0005967956428582452
    dropout_values:
    - 0.5289067419250253
    - 0.4612663627283168
    - 0.3909634953339157
    - 0.6622376807629174
    - 0.3987548854673314
    - 0.7765127753533814
    - 0.6501551199255491
    - 0.3105879102509167
    - 0.4568512578944138
    - 0.4350985542339063
    - 0.4597758462996503
    - 0.33002261445528597
    num_layers_values:
    - 2
    - 3
    - 2
    - 2
    - 3
    - 2
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    weight_decay_values:
    - 0.008669637932271925
    - 2.559642090152666e-06
    - 0.007059178772516602
    - 4.2533702481412986e-05
    - 1.0053602899496827e-05
    - 0.0018020379386416436
    - 0.0006137464129528814
    - 0.00010966483998589818
    - 1.0180379153792234e-05
    - 0.000988901487512057
    - 0.00022327733010992908
    - 0.00012017371812831088
  gasch1_GO:
    hidden_dims:
    - 256
    - 450
    - 324
    - 439
    - 186
    - 255
    - 370
    - 323
    - 444
    - 214
    - 174
    - 413
    lr_values:
    - 0.0004645867951512481
    - 0.0010042849710424865
    - 0.003579964723095651
    - 1.8908974745983059e-06
    - 0.0038608699421558
    - 0.004119826805392098
    - 0.008601337674527393
    - 0.004037132733675168
    - 0.0008593762594647705
    - 0.0026761604236844225
    - 0.0037257981478878337
    - 0.0005967956428582452
    dropout_values:
    - 0.4605568032990952
    - 0.3431912872918102
    - 0.34915416501676766
    - 0.6622376807629174
    - 0.5841459004644107
    - 0.7545983621399663
    - 0.4810194503130645
    - 0.7237861649009504
    - 0.33653840946901864
    - 0.4714634258792045
    - 0.5463347186096245
    - 0.33002261445528597
    num_layers_values:
    - 2
    - 3
    - 2
    - 2
    - 1
    - 2
    - 1
    - 1
    - 1
    - 1
    - 2
    - 1
    weight_decay_values:
    - 1.7414134181586206e-06
    - 7.028699098408326e-06
    - 2.4557202268047003e-06
    - 4.2533702481412986e-05
    - 0.0001400608779843278
    - 0.0009877669239056238
    - 7.007958948093502e-05
    - 0.0002065963827616223
    - 1.2861661122866907e-05
    - 0.0010675777407083322
    - 0.0002523662121929202
    - 0.00012017371812831088
  eisen_FUN:
    hidden_dims:
    - 117
    - 208
    - 191
    - 140
    - 104
    - 232
    lr_values:
    - 0.0004645867951512481
    - 0.004797903275196583
    - 0.004417079211030754
    - 0.0014955151379876697
    - 6.758966622072014e-06
    - 8.449023263251544e-06
    dropout_values:
    - 0.4605568032990952
    - 0.5256352529357294
    - 0.5399086237771014
    - 0.31642263203941073
    - 0.3698158215373223
    - 0.7087369624077865
    num_layers_values:
    - 2
    - 2
    - 2
    - 1
    - 1
    - 1
    weight_decay_values:
    - 1.7414134181586206e-06
    - 3.5177379206759444e-05
    - 2.9992588550226723e-05
    - 1.1860067966373887e-06
    - 1.2666332145532837e-06
    - 0.007019086882635842
  gasch1_FUN:
    hidden_dims:
    - 316
    - 325
    - 282
    - 281
    - 398
    - 507
    lr_values:
    - 4.9501595537331986e-05
    - 0.0012152718138692198
    - 0.0017996633766661863
    - 0.005082631043358049
    - 0.0021095694179648927
    - 8.449023263251544e-06
    dropout_values:
    - 0.6050197648296844
    - 0.44502907121172264
    - 0.6881211142666446
    - 0.336525199553384
    - 0.4106185402664489
    - 0.7087369624077865
    num_layers_values:
    - 2
    - 3
    - 2
    - 2
    - 1
    - 1
    weight_decay_values:
    - 0.00015119336467641018
    - 7.692334691223538e-06
    - 1.5479174758692098e-05
    - 5.913258127478112e-06
    - 0.00022556330753420225
    - 0.007019086882635842
  derisi_GO:
    hidden_dims:
    - 124
    - 118
    - 133
    - 135
    - 67
    - 93
    - 171
    - 67
    - 143
    - 72
    - 89
    - 150
    lr_values:
    - 0.0005336803302756717
    - 6.847105576684053e-06
    - 9.885817165390822e-06
    - 0.007981527604500578
    - 0.0038608699421558
    - 0.004119826805392098
    - 4.255638073105696e-05
    - 1.3589970255431297e-06
    - 0.0011019079505514538
    - 0.006002021558953656
    - 1.1069362598791025e-05
    - 0.0005967956428582452
    dropout_values:
    - 0.5468332247391668
    - 0.4612663627283168
    - 0.3909634953339157
    - 0.46807587334827894
    - 0.5841459004644107
    - 0.7545983621399663
    - 0.640975184076957
    - 0.454721758233509
    - 0.3796293989953052
    - 0.6216180350610268
    - 0.3137682628338999
    - 0.33002261445528597
    num_layers_values:
    - 2
    - 3
    - 2
    - 2
    - 1
    - 2
    - 1
    - 1
    - 2
    - 2
    - 1
    - 1
    weight_decay_values:
    - 0.005956516018710569
    - 2.559642090152666e-06
    - 0.007059178772516602
    - 0.0029209848449546698
    - 0.0001400608779843278
    - 0.0009877669239056238
    - 2.1105981831434946e-06
    - 0.002489735625872539
    - 2.458303050202934e-05
    - 0.0024345360451964444
    - 0.00467484073381124
    - 0.00012017371812831088
  expr_FUN:
    hidden_dims:
    - 1025
    - 979
    - 917
    - 997
    - 1110
    - 660
    lr_values:
    - 4.9501595537331986e-05
    - 0.00032401187009477295
    - 0.0017996633766661863
    - 0.002156086860012146
    - 0.0038124816550143352
    - 0.0003613183893382931
    dropout_values:
    - 0.6050197648296844
    - 0.43160190418464506
    - 0.6881211142666446
    - 0.5215110498614545
    - 0.45350834766166553
    - 0.7858684890159533
    num_layers_values:
    - 2
    - 1
    - 2
    - 1
    - 2
    - 1
    weight_decay_values:
    - 0.00015119336467641018
    - 0.0006963537369571107
    - 1.5479174758692098e-05
    - 0.00014749364398151233
    - 0.0001801975483298418
    - 9.762599247688778e-05
  gasch2_FUN:
    hidden_dims:
    - 57
    - 72
    - 122
    - 92
    - 104
    - 153
    lr_values:
    - 0.0007479352747422678
    - 0.00913442944250835
    - 0.005199848968848456
    - 0.0014955151379876697
    - 5.527691246968043e-06
    - 8.449023263251544e-06
    dropout_values:
    - 0.4334213012463964
    - 0.5400051755100032
    - 0.35705573649464584
    - 0.31642263203941073
    - 0.7060625033126444
    - 0.7087369624077865
    num_layers_values:
    - 2
    - 2
    - 2
    - 1
    - 1
    - 1
    weight_decay_values:
    - 1.7532782487939554e-06
    - 2.4243531469088422e-05
    - 3.125040690876599e-06
    - 1.1860067966373887e-06
    - 0.0015566369519236928
    - 0.007019086882635842
  seq_FUN:
    hidden_dims:
    - 1036
    - 1457
    - 547
    - 1257
    - 887
    - 975
    lr_values:
    - 6.672367170464208e-05
    - 2.0013420622879995e-05
    - 0.004268407710065497
    - 0.002397976129863832
    - 0.003763633748639016
    - 2.4474057445796815e-06
    dropout_values:
    - 0.34398640415917797
    - 0.32720225919695445
    - 0.5600311588276358
    - 0.4235292957731826
    - 0.3730163252220094
    - 0.7514393213097837
    num_layers_values:
    - 1
    - 1
    - 1
    - 1
    - 2
    - 2
    weight_decay_values:
    - 2.9204338471814107e-05
    - 1.5167330688076198e-06
    - 0.00010821382910613992
    - 3.9768137419963324e-05
    - 3.1918291026955788e-06
    - 0.00019065345519393522
