datasets_params:
  expr_GO:
    hidden_dims:
    - - 1156
      - 5
      - 4
      - 9
      - 5
    - - 935
    - - 1932
    - - 1149
    - - 864
    - - 806
    - - 1794
    - - 1494
    - - 1624
      - 360
    - - 1331
    - - 688
      - 5
    - - 1535
      - 2
    lr_values:
    - 3.7446665357415703e-06
    - 3.570522756718297e-06
    - 2.9528914353799858e-05
    - 0.0028537927065418515
    - 0.00031947072076813927
    - 1.665318404271256e-06
    - 0.00015918787344894564
    - 0.00016548218043908931
    - 7.56499779606233e-05
    - 8.147755838659629e-06
    - 0.007602421786884826
    - 0.0019481704579642977
    dropout_values:
    - 0.3369011255912186
    - 0.33430095225136175
    - 0.4580279902905943
    - 0.3938967547851111
    - 0.33298598151342873
    - 0.39108619842552833
    - 0.45027611475156987
    - 0.4982857965959281
    - 0.3762447383335412
    - 0.5925499793682236
    - 0.6659332818944445
    - 0.5481391726620308
    num_layers_values:
    - 5
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 2
    - 1
    - 2
    - 2
    weight_decay_values:
    - 0.00036281404040243816
    - 0.0004220057397195019
    - 0.003856438264681124
    - 0.0002224013329474761
    - 1.7308117471206713e-05
    - 3.3568442943144607e-06
    - 6.781131411387456e-05
    - 4.969995022043841e-05
    - 5.970262645981141e-06
    - 2.3096327448358416e-06
    - 5.7993753026586174e-05
    - 1.9062012964251033e-06
  eisen_FUN:
    hidden_dims:
    - - 237
    - - 89
      - 169
    - - 192
      - 365
    - - 217
      - 201
    - - 110
    - - 126
      - 10
    lr_values:
    - 0.0071556821617548725
    - 1.1522798403028724e-05
    - 0.0007299502772241848
    - 0.00013884530924063992
    - 0.007042802572410074
    - 0.001987941672454878
    dropout_values:
    - 0.4608076967259419
    - 0.5916879510673595
    - 0.44616112836458643
    - 0.750010264467878
    - 0.5156297671607611
    - 0.7611238872059108
    num_layers_values:
    - 1
    - 2
    - 2
    - 2
    - 1
    - 2
    weight_decay_values:
    - 0.0036905577292137633
    - 0.00018467402585753705
    - 0.0003139739202948034
    - 0.0002856694665913656
    - 0.0002177229829567062
    - 6.918664470761978e-05
  gasch1_GO:
    hidden_dims:
    - - 311
      - 7
    - - 288
    - - 308
      - 448
    - - 354
    - - 314
      - 1993
    - - 481
      - 3770
    - - 654
      - 1404
      - 1688
    - - 461
    - - 490
      - 304
    - - 421
      - 77
      - 33
    - - 570
    - - 473
      - 2
    lr_values:
    - 0.0002576638574613588
    - 3.570522756718297e-06
    - 0.008972341368183846
    - 0.0028537927065418515
    - 0.0017178460924168481
    - 0.00011808514427847986
    - 4.386875304900662e-06
    - 0.00016548218043908931
    - 3.105556647768938e-05
    - 0.00045235256902487723
    - 9.251840993214869e-06
    - 0.0019481704579642977
    dropout_values:
    - 0.5139237014900844
    - 0.33430095225136175
    - 0.38294938946806195
    - 0.3938967547851111
    - 0.5590338860409347
    - 0.7281346249782101
    - 0.5598392923184
    - 0.4982857965959281
    - 0.492724907835188
    - 0.5058176223469609
    - 0.48883090265259305
    - 0.5481391726620308
    num_layers_values:
    - 2
    - 1
    - 2
    - 1
    - 2
    - 2
    - 3
    - 1
    - 2
    - 3
    - 1
    - 2
    weight_decay_values:
    - 0.0007257005721594283
    - 0.0004220057397195019
    - 0.0003866349766249224
    - 0.0002224013329474761
    - 4.720190250996815e-05
    - 2.9676586295572792e-05
    - 9.121811502316025e-06
    - 4.969995022043841e-05
    - 1.7439069317055988e-05
    - 2.6123046339678606e-05
    - 0.00021102199215858674
    - 1.9062012964251033e-06
  expr_FUN:
    hidden_dims:
    - - 1156
      - 32
      - 25
      - 53
      - 33
    - - 935
    - - 852
    - - 1884
    - - 1032
    - - 589
      - 7
    lr_values:
    - 3.7446665357415703e-06
    - 3.570522756718297e-06
    - 0.0002664237007197918
    - 0.0010831556229974938
    - 0.0005389282385647377
    - 0.006882296255421993
    dropout_values:
    - 0.3369011255912186
    - 0.33430095225136175
    - 0.5642102133229793
    - 0.6416805614245692
    - 0.6330895167387873
    - 0.40533374740244643
    num_layers_values:
    - 5
    - 1
    - 1
    - 1
    - 1
    - 2
    weight_decay_values:
    - 0.00036281404040243816
    - 0.0004220057397195019
    - 4.9592978717780806e-05
    - 6.174816891114618e-05
    - 8.890073802385806e-05
    - 0.00020425457615643358
  seq_GO:
    hidden_dims:
    - - 951
      - 7
    - - 882
    - - 603
    - - 533
    - - 548
    - - 760
    - - 2086
    - - 1431
    - - 1104
    - - 1255
    - - 653
      - 5
      - 15
      - 16
      - 20
    - - 1448
      - 2
    lr_values:
    - 0.0002576638574613588
    - 3.570522756718297e-06
    - 0.0004271328318436548
    - 0.0009565305756182677
    - 0.0005218163625305433
    - 1.665318404271256e-06
    - 6.113152135565755e-05
    - 0.0002089390996757971
    - 0.00019067386576510745
    - 8.147755838659629e-06
    - 0.004262559485233642
    - 0.0019481704579642977
    dropout_values:
    - 0.5139237014900844
    - 0.33430095225136175
    - 0.579103358135655
    - 0.4168660702654716
    - 0.6821604025309392
    - 0.39108619842552833
    - 0.39139828554960454
    - 0.4791203218104038
    - 0.37046148754573954
    - 0.5925499793682236
    - 0.6430883571982395
    - 0.5481391726620308
    num_layers_values:
    - 2
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 5
    - 2
    weight_decay_values:
    - 0.0007257005721594283
    - 0.0004220057397195019
    - 0.00010280381438160046
    - 0.00014883549249771548
    - 7.843034987172757e-05
    - 3.3568442943144607e-06
    - 9.342162113819164e-06
    - 1.2023611263437412e-05
    - 4.947201990319362e-05
    - 2.3096327448358416e-06
    - 2.11683305819999e-05
    - 1.9062012964251033e-06
  cellcycle_GO:
    hidden_dims:
    - - 138
      - 7
    - - 87
      - 73
    - - 132
      - 434
    - - 157
    - - 298
      - 2414
    - - 277
      - 4256
    - - 291
      - 1404
      - 1688
    - - 205
    - - 202
    - - 187
    - - 237
      - 13
      - 20
    - - 211
      - 2
    lr_values:
    - 0.0002576638574613588
    - 1.1522798403028724e-05
    - 0.0058892513127002935
    - 0.0028537927065418515
    - 0.000683327228258257
    - 4.9380643246999196e-05
    - 4.386875304900662e-06
    - 0.00016548218043908931
    - 0.007097105797471035
    - 0.0003548338753611589
    - 0.00023026581494425412
    - 0.0019481704579642977
    dropout_values:
    - 0.5139237014900844
    - 0.5916879510673595
    - 0.39334227837823244
    - 0.3938967547851111
    - 0.4539253508729626
    - 0.5904470494978219
    - 0.5598392923184
    - 0.4982857965959281
    - 0.540591950655871
    - 0.3171215657815094
    - 0.3654293687446122
    - 0.5481391726620308
    num_layers_values:
    - 2
    - 2
    - 2
    - 1
    - 2
    - 2
    - 3
    - 1
    - 1
    - 1
    - 3
    - 2
    weight_decay_values:
    - 0.0007257005721594283
    - 0.00018467402585753705
    - 0.00036266280248390114
    - 0.0002224013329474761
    - 3.868957417230927e-05
    - 2.6855216380571683e-05
    - 9.121811502316025e-06
    - 4.969995022043841e-05
    - 0.00022644276012169772
    - 1.0072179140628842e-06
    - 9.895879688552623e-06
    - 1.9062012964251033e-06
  cellcycle_FUN:
    hidden_dims:
    - - 231
    - - 87
      - 177
    - - 190
      - 439
    - - 127
    - - 167
    - - 201
      - 9
    lr_values:
    - 0.0071556821617548725
    - 1.1522798403028724e-05
    - 0.00023093568402608448
    - 0.001071154414218174
    - 0.0038000204659583733
    - 0.001069260198199776
    dropout_values:
    - 0.4608076967259419
    - 0.5916879510673595
    - 0.40195755787109927
    - 0.3413254262732386
    - 0.4880367511005182
    - 0.4150803205208824
    num_layers_values:
    - 1
    - 2
    - 2
    - 1
    - 1
    - 2
    weight_decay_values:
    - 0.0036905577292137633
    - 0.00018467402585753705
    - 0.00019048450023136226
    - 0.00022173137484116738
    - 0.00015932562998464476
    - 2.7904689426884485e-06
  eisen_GO:
    hidden_dims:
    - - 142
      - 7
    - - 131
    - - 120
    - - 207
      - 826
    - - 110
    - - 140
      - 2251
    - - 299
      - 1207
      - 1452
    - - 217
    - - 261
    - - 187
    - - 79
      - 10
      - 11
      - 14
      - 14
    lr_values:
    - 0.0002576638574613588
    - 3.570522756718297e-06
    - 0.0002664237007197918
    - 0.0010365731307907275
    - 0.007042802572410074
    - 0.0023443657448656403
    - 4.386875304900662e-06
    - 0.001290420791930368
    - 0.001739319074844699
    - 8.147755838659629e-06
    - 5.258249597471557e-05
    dropout_values:
    - 0.5139237014900844
    - 0.33430095225136175
    - 0.5642102133229793
    - 0.4115915604507161
    - 0.5156297671607611
    - 0.5228378817224112
    - 0.5598392923184
    - 0.6969718551511371
    - 0.4880371528872294
    - 0.5925499793682236
    - 0.5869464981274243
    num_layers_values:
    - 2
    - 1
    - 1
    - 2
    - 1
    - 2
    - 3
    - 1
    - 1
    - 1
    - 5
    weight_decay_values:
    - 0.0007257005721594283
    - 0.0004220057397195019
    - 4.9592978717780806e-05
    - 0.00012169394901414475
    - 0.0002177229829567062
    - 9.854591100746911e-05
    - 9.121811502316025e-06
    - 0.00011543785724055714
    - 0.00031390414340036715
    - 2.3096327448358416e-06
    - 1.4515281940131885e-05
  spo_GO:
    hidden_dims:
    - - 154
      - 7
    - - 97
      - 73
    - - 228
      - 417
    - - 296
      - 2384
    - - 155
      - 1676
    - - 336
      - 4084
    - - 268
      - 2616
    - - 253
      - 1480
    - - 141
      - 626
      - 348
      - 282
      - 193
    - - 98
      - 60
      - 67
    - - 105
    - - 235
      - 2
    lr_values:
    - 0.0002576638574613588
    - 1.1522798403028724e-05
    - 0.008016101856312038
    - 0.0017387795401398187
    - 0.0040537898794657835
    - 5.0273650187527385e-05
    - 0.006419451282568034
    - 7.288932333875749e-05
    - 0.007719772810165619
    - 2.1670028294992215e-05
    - 0.0006208603298241612
    - 0.0019481704579642977
    dropout_values:
    - 0.5139237014900844
    - 0.5916879510673595
    - 0.40096139212488074
    - 0.5330717518067377
    - 0.4567054248035964
    - 0.5855768965023209
    - 0.6957997720100111
    - 0.5393265701389407
    - 0.7960163403431376
    - 0.6663814783239598
    - 0.7180348618960305
    - 0.5481391726620308
    num_layers_values:
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 2
    - 5
    - 3
    - 1
    - 2
    weight_decay_values:
    - 0.0007257005721594283
    - 0.00018467402585753705
    - 0.00033378198361136576
    - 0.00010008482802859485
    - 4.155286725523268e-05
    - 3.208814715426559e-05
    - 6.743631232960267e-05
    - 0.00013043335141725882
    - 0.00066164210534599
    - 0.00010945328146952068
    - 0.001143530881597074
    - 1.9062012964251033e-06
  derisi_FUN:
    hidden_dims:
    - - 113
      - 44
    - - 71
      - 177
    - - 156
      - 439
    - - 171
      - 248
    - - 94
      - 250
      - 181
      - 78
    - - 114
      - 4
      - 6
      - 16
    lr_values:
    - 0.0002576638574613588
    - 1.1522798403028724e-05
    - 0.00023093568402608448
    - 0.00034990941806506084
    - 0.00033250007489809034
    - 4.521892338748271e-05
    dropout_values:
    - 0.5139237014900844
    - 0.5916879510673595
    - 0.40195755787109927
    - 0.48314455053404365
    - 0.7552986738801433
    - 0.3059941817004675
    num_layers_values:
    - 2
    - 2
    - 2
    - 2
    - 4
    - 4
    weight_decay_values:
    - 0.0007257005721594283
    - 0.00018467402585753705
    - 0.00019048450023136226
    - 0.0002178407381083326
    - 0.0015732956772590587
    - 8.470063804797612e-06
  derisi_GO:
    hidden_dims:
    - - 113
      - 7
    - - 71
      - 73
    - - 156
      - 429
    - - 176
      - 1277
      - 886
      - 920
      - 701
    - - 64
      - 1969
      - 862
    - - 249
      - 1067
      - 4239
    - - 97
      - 1442
      - 2470
      - 768
    - - 190
      - 1312
    - - 235
      - 191
      - 468
    - - 72
      - 60
      - 67
    - - 156
      - 17
      - 5
    - - 172
      - 2
    lr_values:
    - 0.0002576638574613588
    - 1.1522798403028724e-05
    - 0.00023093568402608448
    - 5.556125201132276e-06
    - 0.0005292529919163857
    - 0.00022035933104979326
    - 0.0001327496644496176
    - 0.0001273220987932232
    - 0.0006040599239238169
    - 2.1670028294992215e-05
    - 3.901527808971197e-06
    - 0.0019481704579642977
    dropout_values:
    - 0.5139237014900844
    - 0.5916879510673595
    - 0.40195755787109927
    - 0.44335435186388333
    - 0.6735144472941308
    - 0.6257494446357548
    - 0.5974704589773547
    - 0.5525579971152033
    - 0.3360525647956368
    - 0.6663814783239598
    - 0.44404222967659834
    - 0.5481391726620308
    num_layers_values:
    - 2
    - 2
    - 2
    - 5
    - 3
    - 3
    - 4
    - 2
    - 3
    - 3
    - 3
    - 2
    weight_decay_values:
    - 0.0007257005721594283
    - 0.00018467402585753705
    - 0.00019048450023136226
    - 6.908360556635798e-06
    - 4.9673204849414426e-05
    - 5.270224465840359e-05
    - 2.6637326030125917e-05
    - 0.00011598182718180072
    - 0.0002034983892855782
    - 0.00010945328146952068
    - 3.321549539245794e-05
    - 1.9062012964251033e-06
  gasch1_FUN:
    hidden_dims:
    - - 518
    - - 197
      - 177
    - - 211
    - - 354
    - - 293
    - - 570
      - 11
    lr_values:
    - 0.0071556821617548725
    - 1.1522798403028724e-05
    - 0.0006142024873399306
    - 0.0028537927065418515
    - 0.001606474345917984
    - 4.810141660728995e-05
    dropout_values:
    - 0.4608076967259419
    - 0.5916879510673595
    - 0.32813484713919205
    - 0.3938967547851111
    - 0.47752546815893826
    - 0.5799527435199452
    num_layers_values:
    - 1
    - 2
    - 1
    - 1
    - 1
    - 2
    weight_decay_values:
    - 0.0036905577292137633
    - 0.00018467402585753705
    - 0.00012765700818102795
    - 0.0002224013329474761
    - 8.470076321389111e-06
    - 9.582279610728686e-06
  spo_FUN:
    hidden_dims:
    - - 258
    - - 97
      - 177
    - - 212
      - 439
    - - 237
      - 218
    - - 141
    - - 253
      - 12
      - 5
    lr_values:
    - 0.0071556821617548725
    - 1.1522798403028724e-05
    - 0.00023093568402608448
    - 0.00013884530924063992
    - 0.0040528914941275074
    - 1.688077206274809e-06
    dropout_values:
    - 0.4608076967259419
    - 0.5916879510673595
    - 0.40195755787109927
    - 0.750010264467878
    - 0.386642902238313
    - 0.3583322530478644
    num_layers_values:
    - 1
    - 2
    - 2
    - 2
    - 1
    - 3
    weight_decay_values:
    - 0.0036905577292137633
    - 0.00018467402585753705
    - 0.00019048450023136226
    - 0.0002856694665913656
    - 5.3343638084340927e-05
    - 0.0014262053105271546
  gasch2_GO:
    hidden_dims:
    - - 93
      - 7
    - - 59
      - 73
    - - 94
      - 367
    - - 145
      - 1277
      - 886
      - 920
      - 701
    - - 71
    - - 142
      - 1138
    - - 197
      - 1406
      - 1690
    - - 157
      - 1477
    - - 147
      - 304
    - - 52
    - - 171
    - - 142
      - 2
    lr_values:
    - 0.0002576638574613588
    - 1.1522798403028724e-05
    - 0.007638734245943353
    - 5.556125201132276e-06
    - 0.0030500572831398537
    - 0.00013659601693231116
    - 4.386875304900662e-06
    - 8.220740926274329e-05
    - 3.105556647768938e-05
    - 0.001901084446176793
    - 9.251840993214869e-06
    - 0.0019481704579642977
    dropout_values:
    - 0.5139237014900844
    - 0.5916879510673595
    - 0.4006486097821617
    - 0.44335435186388333
    - 0.3917425817340373
    - 0.710431323376329
    - 0.5598392923184
    - 0.5496674962213892
    - 0.492724907835188
    - 0.7972637886909462
    - 0.48883090265259305
    - 0.5481391726620308
    num_layers_values:
    - 2
    - 2
    - 2
    - 5
    - 1
    - 2
    - 3
    - 2
    - 2
    - 1
    - 1
    - 2
    weight_decay_values:
    - 0.0007257005721594283
    - 0.00018467402585753705
    - 0.00028707342623450396
    - 6.908360556635798e-06
    - 1.4679493648917919e-05
    - 2.4210098768071565e-05
    - 9.121811502316025e-06
    - 0.00011170977127149728
    - 1.7439069317055988e-05
    - 4.405580323028443e-05
    - 0.00021102199215858674
    - 1.9062012964251033e-06
  gasch2_FUN:
    hidden_dims:
    - - 93
      - 44
    - - 59
      - 177
    - - 128
      - 439
    - - 124
    - - 103
      - 187
    - - 58
    lr_values:
    - 0.0002576638574613588
    - 1.1522798403028724e-05
    - 0.00023093568402608448
    - 0.004186231636583526
    - 0.00845897145203795
    - 3.870673878357345e-06
    dropout_values:
    - 0.5139237014900844
    - 0.5916879510673595
    - 0.40195755787109927
    - 0.49557498306310377
    - 0.42172745605929396
    - 0.30338143050065336
    num_layers_values:
    - 2
    - 2
    - 2
    - 1
    - 2
    - 1
    weight_decay_values:
    - 0.0007257005721594283
    - 0.00018467402585753705
    - 0.00019048450023136226
    - 0.0001835546063891636
    - 3.913482929614151e-06
    - 0.0012087124459722353
  seq_FUN:
    hidden_dims:
    - - 1746
    - - 882
    - - 778
    - - 2031
    - - 658
    - - 1744
      - 11
    lr_values:
    - 0.00017716018522574196
    - 3.570522756718297e-06
    - 0.0017220457830658014
    - 0.001241104181067227
    - 0.0007483273176660007
    - 4.810141660728995e-05
    dropout_values:
    - 0.3804518415558637
    - 0.33430095225136175
    - 0.4869218137303768
    - 0.6507067788912798
    - 0.7219015740473292
    - 0.5799527435199452
    num_layers_values:
    - 1
    - 1
    - 1
    - 1
    - 1
    - 2
    weight_decay_values:
    - 0.005067473805402052
    - 0.0004220057397195019
    - 0.0001503887438298743
    - 1.7026948254830658e-05
    - 9.735247026819912e-05
    - 9.582279610728686e-06
  
