datasets_params:
  derisi_FUN:
    hidden_dims:
    - - 172
      - 85
    - - 123
      - 173
    - - 114
    - - 113
    - - 105
    - - 84
    lr_values:
    - 0.0005585265861247852
    - 0.0026766747773208015
    - 0.0028884922998678427
    - 0.0005218805290744773
    - 2.2147779484607625e-05
    - 1.665318404271256e-06
    dropout_values:
    - 0.7066340177021514
    - 0.5861569917567994
    - 0.38575717119982483
    - 0.30735028584686075
    - 0.33389499388223026
    - 0.39108619842552833
    num_layers_values:
    - 2
    - 2
    - 1
    - 1
    - 1
    - 1
    weight_decay_values:
    - 0.00010862835548996536
    - 3.717611822749835e-05
    - 0.00011732052334667398
    - 1.8577981490658547e-06
    - 0.0033125927234181857
    - 3.3568442943144607e-06
  cellcycle_GO:
    hidden_dims:
    - - 122
      - 156
    - - 188
    - - 136
      - 134
    - - 90
      - 193
    - - 133
      - 155
    - - 136
    - - 221
    - - 155
    - - 152
      - 168
      - 96
    - - 85
      - 125
      - 136
    - - 112
    - - 171
      - 139
    lr_values:
    - 0.0002576638574613588
    - 0.0009146401185609088
    - 0.004302231363370785
    - 0.0026225599002628764
    - 0.00845897145203795
    - 0.001581916435704676
    - 0.002489735625872539
    - 0.0062006757624607604
    - 0.0009128304157771137
    - 2.1670028294992215e-05
    - 3.4178872103448533e-06
    - 0.0019481704579642977
    dropout_values:
    - 0.5139237014900844
    - 0.6615616140985289
    - 0.7885428074738768
    - 0.36606919910949304
    - 0.42172745605929396
    - 0.4709832720713575
    - 0.454721758233509
    - 0.4177889065413218
    - 0.3324217747860466
    - 0.6663814783239598
    - 0.41771114915377544
    - 0.5481391726620308
    num_layers_values:
    - 2
    - 1
    - 2
    - 2
    - 2
    - 1
    - 1
    - 1
    - 3
    - 3
    - 1
    - 2
    weight_decay_values:
    - 0.0007257005721594283
    - 6.457406519164194e-05
    - 6.580811687034913e-06
    - 1.52266197715195e-05
    - 3.913482929614151e-06
    - 1.508166205449147e-06
    - 1.0832688814574871e-05
    - 1.7010119855124928e-05
    - 2.4768742383683374e-05
    - 0.00010945328146952068
    - 0.007620347466164901
    - 1.9062012964251033e-06
  expr_GO:
    hidden_dims:
    - - 893
      - 1140
    - - 1438
      - 884
    - - 1346
    - - 990
    - - 998
    - - 1234
      - 1174
      - 1599
    - - 1609
    - - 792
    - - 1144
      - 1264
      - 622
    - - 1290
      - 1494
    - - 818
    - - 1246
      - 1012
    lr_values:
    - 0.0002576638574613588
    - 4.623135641589657e-05
    - 0.0014631581250503518
    - 0.0028537927065418515
    - 0.0005382895350115236
    - 0.0004990612617942653
    - 0.002489735625872539
    - 0.0022222919091487788
    - 0.0011490444409273926
    - 0.0017560484713502425
    - 3.4178872103448533e-06
    - 0.0019481704579642977
    dropout_values:
    - 0.5139237014900844
    - 0.46876875602074297
    - 0.7954226648145604
    - 0.3938967547851111
    - 0.5629911874540939
    - 0.7716738239690402
    - 0.454721758233509
    - 0.6042887126147385
    - 0.3197920767206951
    - 0.4988100360747967
    - 0.41771114915377544
    - 0.5481391726620308
    num_layers_values:
    - 2
    - 2
    - 1
    - 1
    - 1
    - 3
    - 1
    - 1
    - 3
    - 2
    - 1
    - 2
    weight_decay_values:
    - 0.0007257005721594283
    - 0.0016886125549854716
    - 0.00026774381763209487
    - 0.0002224013329474761
    - 5.890861425878144e-05
    - 7.336911791470889e-06
    - 1.0832688814574871e-05
    - 1.5824946884071114e-05
    - 1.4260526308658922e-05
    - 1.1083862819829996e-05
    - 0.007620347466164901
    - 1.9062012964251033e-06
  eisen_GO:
    hidden_dims:
    - - 125
      - 160
    - - 187
    - - 82
    - - 224
    - - 138
    - - 207
    - - 150
      - 237
    - - 164
    - - 152
    - - 87
      - 128
      - 140
    - - 115
    lr_values:
    - 0.0002576638574613588
    - 0.0027586790343207958
    - 0.0004895799771977815
    - 0.0009875576143557245
    - 0.001942991643522893
    - 0.0013633282069552093
    - 0.009640619396946002
    - 0.0004467024003257223
    - 0.0002123198408088043
    - 2.1670028294992215e-05
    - 3.4178872103448533e-06
    dropout_values:
    - 0.5139237014900844
    - 0.6306004539719158
    - 0.46474132230758397
    - 0.4326378285766908
    - 0.4306523011080911
    - 0.5199370229390963
    - 0.6164344421463624
    - 0.3980796685001305
    - 0.3634857119521152
    - 0.6663814783239598
    - 0.41771114915377544
    num_layers_values:
    - 2
    - 1
    - 1
    - 1
    - 1
    - 1
    - 2
    - 1
    - 1
    - 3
    - 1
    weight_decay_values:
    - 0.0007257005721594283
    - 1.4674591036981037e-05
    - 1.7359244600909264e-05
    - 3.5481431508474895e-05
    - 3.5285890879221236e-06
    - 7.866913985838826e-06
    - 6.601296807675679e-06
    - 9.24005338318659e-06
    - 9.110942347954227e-06
    - 0.00010945328146952068
    - 0.007620347466164901
  spo_GO:
    hidden_dims:
    - - 137
      - 175
    - - 115
    - - 204
      - 167
      - 245
      - 88
    - - 113
      - 108
      - 152
    - - 196
      - 232
      - 94
    - - 159
    - - 247
    - - 194
    - - 170
      - 188
      - 107
    - - 95
      - 139
      - 152
    - - 148
      - 87
    - - 191
      - 155
    lr_values:
    - 0.0002576638574613588
    - 0.007065082527006584
    - 0.008624491517985982
    - 0.006158605166039836
    - 0.00577733806073296
    - 0.0037120495628467534
    - 0.002489735625872539
    - 0.0008060179264223223
    - 0.0009128304157771137
    - 2.1670028294992215e-05
    - 1.6138797631151e-06
    - 0.0019481704579642977
    dropout_values:
    - 0.5139237014900844
    - 0.797817917217779
    - 0.35479665840106794
    - 0.5888026612791595
    - 0.4841924016682428
    - 0.588205672396
    - 0.454721758233509
    - 0.41211605941317236
    - 0.3324217747860466
    - 0.6663814783239598
    - 0.5682740016507543
    - 0.5481391726620308
    num_layers_values:
    - 2
    - 1
    - 4
    - 3
    - 3
    - 1
    - 1
    - 1
    - 3
    - 3
    - 2
    - 2
    weight_decay_values:
    - 0.0007257005721594283
    - 8.172090702669466e-06
    - 3.59862157396732e-06
    - 7.278312668139317e-06
    - 2.6451539379357914e-05
    - 1.1148529625650664e-05
    - 1.0832688814574871e-05
    - 1.961230915425423e-05
    - 2.4768742383683374e-05
    - 0.00010945328146952068
    - 0.000310115666020329
    - 1.9062012964251033e-06
  gasch2_GO:
    hidden_dims:
    - - 82
      - 106
    - - 107
    - - 106
      - 106
    - - 63
    - - 91
    - - 102
    - - 156
    - - 144
    - - 135
    - - 57
      - 84
      - 92
    - - 75
    - - 82
      - 106
    lr_values:
    - 0.0002576638574613588
    - 0.0040819565285021495
    - 0.00023093568402608448
    - 0.000610061973433681
    - 0.001942991643522893
    - 0.003867373376534648
    - 0.001993328307576355
    - 0.0036025646732947857
    - 0.002578666018013965
    - 2.1670028294992215e-05
    - 3.4178872103448533e-06
    - 0.0002576638574613588
    dropout_values:
    - 0.5139237014900844
    - 0.5011157086534973
    - 0.40195755787109927
    - 0.4593769013713677
    - 0.4306523011080911
    - 0.46762936969780566
    - 0.4994685205778641
    - 0.388196152474965
    - 0.397448403728802
    - 0.6663814783239598
    - 0.41771114915377544
    - 0.5139237014900844
    num_layers_values:
    - 2
    - 1
    - 2
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    - 3
    - 1
    - 2
    weight_decay_values:
    - 0.0007257005721594283
    - 5.776878295776488e-05
    - 0.00019048450023136226
    - 1.76678428617175e-05
    - 3.5285890879221236e-06
    - 7.706421716987967e-06
    - 1.0012229662635549e-06
    - 1.4561234775947908e-05
    - 1.8527516256812318e-06
    - 0.00010945328146952068
    - 0.007620347466164901
    - 0.0007257005721594283
  cellcycle_FUN:
    hidden_dims:
    - - 164
      - 226
    - - 111
      - 77
      - 231
    - - 95
      - 139
    - - 151
    - - 91
      - 121
    - - 102
    lr_values:
    - 0.0005324032819679062
    - 0.001730364971319547
    - 0.0035964261845707743
    - 0.0009998107149772537
    - 0.009297852553430498
    - 1.665318404271256e-06
    dropout_values:
    - 0.6593978084168616
    - 0.319155073340526
    - 0.3310573198442008
    - 0.5554971230738751
    - 0.35597085058674816
    - 0.39108619842552833
    num_layers_values:
    - 2
    - 3
    - 2
    - 1
    - 2
    - 1
    weight_decay_values:
    - 6.149340416365067e-05
    - 5.5419996305923144e-05
    - 1.0731215793432283e-05
    - 2.9586682511572486e-06
    - 6.66738562367692e-06
    - 3.3568442943144607e-06
  spo_FUN:
    hidden_dims:
    - - 137
      - 175
    - - 256
      - 91
    - - 128
    - - 110
      - 215
    - - 204
      - 117
    - - 144
    lr_values:
    - 0.0002576638574613588
    - 0.006259670793727615
    - 0.007765335724810954
    - 0.0036864348472535717
    - 0.005225372642279878
    - 2.116754876441349e-05
    dropout_values:
    - 0.5139237014900844
    - 0.7700456582059304
    - 0.45209219968345454
    - 0.33522968703459893
    - 0.331011695016847
    - 0.4172724996653199
    num_layers_values:
    - 2
    - 2
    - 1
    - 2
    - 2
    - 1
    weight_decay_values:
    - 0.0007257005721594283
    - 1.0170100575791454e-06
    - 1.5369971652548922e-05
    - 2.803485015816864e-06
    - 1.1633717625636615e-06
    - 4.0605759249278814e-06
  seq_GO:
    hidden_dims:
    - - 842
      - 1075
    - - 1162
    - - 701
    - - 553
    - - 822
    - - 779
      - 1307
      - 1036
    - - 1106
    - - 1150
    - - 1354
    - - 730
      - 1075
      - 710
    - - 771
    - - 1175
      - 954
    lr_values:
    - 0.0002576638574613588
    - 0.00046734921748237286
    - 0.0009897156541608938
    - 0.001632770991519783
    - 0.00047885946489080407
    - 0.002082552711143654
    - 0.000529537119448294
    - 0.00016548218043908931
    - 0.001421756309313839
    - 0.003888274723870115
    - 3.4178872103448533e-06
    - 0.0019481704579642977
    dropout_values:
    - 0.5139237014900844
    - 0.7464012841213854
    - 0.3619473605639932
    - 0.4916270216427237
    - 0.48164553965457935
    - 0.5193564837598
    - 0.4596579733735099
    - 0.4982857965959281
    - 0.6773487442719379
    - 0.4247682473807237
    - 0.41771114915377544
    - 0.5481391726620308
    num_layers_values:
    - 2
    - 1
    - 1
    - 1
    - 1
    - 3
    - 1
    - 1
    - 1
    - 3
    - 1
    - 2
    weight_decay_values:
    - 0.0007257005721594283
    - 1.8805107040212936e-05
    - 0.00016854060700180652
    - 7.56757667669938e-05
    - 6.594369621404704e-05
    - 5.364111261553656e-06
    - 4.051055037240015e-06
    - 4.969995022043841e-05
    - 0.00015409147026945413
    - 2.9314809202851584e-05
    - 0.007620347466164901
    - 1.9062012964251033e-06
  gasch1_GO:
    hidden_dims:
    - - 275
      - 352
    - - 280
    - - 191
    - - 210
    - - 312
    - - 371
      - 506
      - 324
    - - 497
    - - 438
      - 402
    - - 343
      - 378
      - 216
    - - 209
    - - 252
    - - 384
      - 312
    lr_values:
    - 0.0002576638574613588
    - 0.0027325771132837573
    - 0.0009592990660857501
    - 0.000610061973433681
    - 0.0008818340052977309
    - 0.001295983956227868
    - 0.002489735625872539
    - 0.0013934523812062305
    - 0.0009128304157771137
    - 0.004776736040638315
    - 3.4178872103448533e-06
    - 0.0019481704579642977
    dropout_values:
    - 0.5139237014900844
    - 0.6108934491848114
    - 0.5680401405736762
    - 0.4593769013713677
    - 0.30258967946103466
    - 0.7164481146295658
    - 0.454721758233509
    - 0.414658123292892
    - 0.3324217747860466
    - 0.6770669030018764
    - 0.41771114915377544
    - 0.5481391726620308
    num_layers_values:
    - 2
    - 1
    - 1
    - 1
    - 1
    - 3
    - 1
    - 2
    - 3
    - 1
    - 1
    - 2
    weight_decay_values:
    - 0.0007257005721594283
    - 5.9791899060174206e-05
    - 0.00011195592301047818
    - 1.76678428617175e-05
    - 2.74273927246084e-05
    - 1.8395224412945302e-06
    - 1.0832688814574871e-05
    - 2.9885983593304687e-05
    - 2.4768742383683374e-05
    - 0.0074669912287723475
    - 0.007620347466164901
    - 1.9062012964251033e-06
  eisen_FUN:
    hidden_dims:
    - - 125
      - 160
    - - 118
      - 83
      - 230
    - - 129
      - 125
      - 135
    - - 96
    - - 136
      - 159
    - - 186
      - 186
      - 105
    lr_values:
    - 0.0002576638574613588
    - 0.003670655015223565
    - 0.0038453443414358775
    - 0.000610061973433681
    - 0.00845897145203795
    - 1.688077206274809e-06
    dropout_values:
    - 0.5139237014900844
    - 0.35788793762844884
    - 0.4482141568392264
    - 0.4593769013713677
    - 0.42172745605929396
    - 0.3583322530478644
    num_layers_values:
    - 2
    - 3
    - 3
    - 1
    - 2
    - 3
    weight_decay_values:
    - 0.0007257005721594283
    - 7.047894651804028e-05
    - 1.0386561204194402e-05
    - 1.76678428617175e-05
    - 3.913482929614151e-06
    - 0.0014262053105271546
  gasch1_FUN:
    hidden_dims:
    - - 275
      - 352
    - - 185
    - - 323
      - 270
      - 186
    - - 330
    - - 420
      - 275
    - - 306
    lr_values:
    - 0.0002576638574613588
    - 1.8703923501768496e-05
    - 0.002466226257421433
    - 0.0016697312293557597
    - 0.004204400569301354
    - 0.001581916435704676
    dropout_values:
    - 0.5139237014900844
    - 0.4011139066197706
    - 0.5486942157514224
    - 0.45844739783603633
    - 0.45838814256169613
    - 0.4709832720713575
    num_layers_values:
    - 2
    - 1
    - 3
    - 1
    - 2
    - 1
    weight_decay_values:
    - 0.0007257005721594283
    - 2.984770033451217e-06
    - 3.1280949806988417e-06
    - 3.2036267093529595e-05
    - 1.7263700014202442e-06
    - 1.508166205449147e-06
  derisi_GO:
    hidden_dims:
    - - 100
      - 128
    - - 120
      - 94
      - 64
    - - 63
      - 108
    - - 156
      - 137
    - - 143
      - 170
      - 69
    - - 122
      - 183
      - 63
      - 178
    - - 108
    - - 108
      - 118
    - - 73
    - - 70
      - 102
      - 111
    - - 91
    - - 140
      - 113
    lr_values:
    - 0.0002576638574613588
    - 0.0011553211172058407
    - 0.0013650753361556806
    - 0.0006173765958956214
    - 0.00577733806073296
    - 0.0039208490941786715
    - 0.002987319040569983
    - 0.0007421698652077056
    - 5.944929375537721e-06
    - 2.1670028294992215e-05
    - 3.4178872103448533e-06
    - 0.0019481704579642977
    dropout_values:
    - 0.5139237014900844
    - 0.4361780239541792
    - 0.787491921098519
    - 0.647845513494599
    - 0.4841924016682428
    - 0.3055023965036348
    - 0.4047873798986403
    - 0.41434691852608363
    - 0.6577992693002903
    - 0.6663814783239598
    - 0.41771114915377544
    - 0.5481391726620308
    num_layers_values:
    - 2
    - 3
    - 2
    - 2
    - 3
    - 4
    - 1
    - 2
    - 1
    - 3
    - 1
    - 2
    weight_decay_values:
    - 0.0007257005721594283
    - 5.4093238806666606e-05
    - 5.086839103032552e-06
    - 4.816837567103389e-06
    - 2.6451539379357914e-05
    - 0.0005513619000667136
    - 6.990045477536246e-06
    - 0.009830892624384188
    - 0.0013546892122750828
    - 0.00010945328146952068
    - 0.007620347466164901
    - 1.9062012964251033e-06
  expr_FUN:
    hidden_dims:
    - - 995
      - 884
      - 750
      - 1313
      - 926
    - - 841
    - - 781
    - - 644
    - - 935
    - - 696
    lr_values:
    - 3.7446665357415703e-06
    - 3.570522756718297e-06
    - 0.0002664237007197918
    - 0.0010226901834924462
    - 0.0014353045876036006
    - 1.2339217221900532e-05
    dropout_values:
    - 0.3369011255912186
    - 0.33430095225136175
    - 0.5642102133229793
    - 0.44973753818417583
    - 0.46048334517735073
    - 0.4328664866349849
    num_layers_values:
    - 5
    - 1
    - 1
    - 1
    - 1
    - 1
    weight_decay_values:
    - 0.00036281404040243816
    - 0.0004220057397195019
    - 4.9592978717780806e-05
    - 0.00018507096627635067
    - 1.0140484572765254e-06
    - 0.00022407764978418478
  gasch2_FUN:
    hidden_dims:
    - - 87
      - 74
    - - 133
      - 60
    - - 93
      - 122
      - 131
    - - 70
      - 93
    - - 122
      - 121
    - - 57
    lr_values:
    - 0.001068867264477601
    - 0.003225167526615667
    - 0.0028423672432035816
    - 0.0037710600733101116
    - 0.0038426813990934242
    - 3.870673878357345e-06
    dropout_values:
    - 0.35287542530614224
    - 0.3223594026862116
    - 0.36744607978292
    - 0.43872056947036997
    - 0.32880984029567323
    - 0.30338143050065336
    num_layers_values:
    - 2
    - 2
    - 3
    - 2
    - 2
    - 1
    weight_decay_values:
    - 0.0006816294322545899
    - 0.0001468428292617701
    - 4.119075990944701e-06
    - 4.977031099498455e-06
    - 7.993154642363986e-06
    - 0.0012087124459722353
  seq_FUN:
    hidden_dims:
    - - 729
    - - 793
    - - 736
    - - 568
    - - 1051
    - - 1245
      - 9
      - 5
    lr_values:
    - 0.00017114004593883324
    - 3.570522756718297e-06
    - 0.0002664237007197918
    - 0.0004330792219073239
    - 0.0002480244014313203
    - 1.688077206274809e-06
    dropout_values:
    - 0.34279493966884744
    - 0.33430095225136175
    - 0.5642102133229793
    - 0.5117080668730427
    - 0.7240228615634108
    - 0.3583322530478644
    num_layers_values:
    - 1
    - 1
    - 1
    - 1
    - 1
    - 3
    weight_decay_values:
    - 0.0007921247055617449
    - 0.0004220057397195019
    - 4.9592978717780806e-05
    - 5.853875100602162e-05
    - 1.8598517327403467e-05
    - 0.0014262053105271546
